### ISSUE TITLE
Consume XCFramework & *.podspec structure

### ISSUE THREAD

**Issue by 6epreu** [CocoaPods/CocoaPods#10461]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Im creating the *.xcframework and trying to consume it in client application using *.podspec file
The actual xcframework compiled succesfully
*.podspec

```
Pod::Spec.new do |spec|
    spec.name         = "UnitTestWithPod"
    spec.version = "1.2.3"
    spec.summary      = "A really short description of test_sic. Included some specific points"
    spec.description  = "777"
    spec.homepage     = "https://github.com/LLTemp/test_sic_zip"
    spec.license      = "MIT"
    spec.author       = { "SergeyBrazhnik" => "sergey.brazhnik@ll.com" }
    spec.platform     = :ios, "14.0"
    #spec.source = { :http => "[REPLACE_ME]" }
    spec.source = { :http => "https://testbuildartefacts.s3.us-east-2.amazonaws.com/sic-sdk-ios/1.2.3/UnitTestWithPod.xcframework.zip", :type => "zip" }
    spec.vendored_framework = 'UnitTestWithPod.xcframework'
    spec.vendored_libraries = 'UnitTestWithPod.xcframework/lib'
    spec.header_mappings_dir = 'UnitTestWithPod.xcframework/openssl'
    spec.dependency 'KeychainSwift', '~> 19.0'
    spec.dependency 'gRPC-Swift', '1.0.0'
end
```

Podfile
```
platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'

target 'UnitTestWithPodAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for UnitTestWithPodAPP
  pod 'UnitTestWithPod', :path => '../UnitTestWithPod/'
end
```

## What did you expect to happen?
Project compiles successfuly

## What happened instead?
![2021-02-25_19-30-48](https://user-images.githubusercontent.com/1928745/109184383-0064a280-77a0-11eb-9de6-940acfa229f7.png)

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2 (20D64)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue
https://github.com/LLTemp/UnitTestRepo

**Comment by BentoNight** [comment]
Same problem

**Comment by Gray-Wind** [comment]
I have the same problem. I cannot find any workaround, does anybody know how to solve it?

**Comment by alexeybolv** [comment]
Have the same error, did you find any solutions?

**Comment by Gray-Wind** [comment]
In my case it turned out that I needed to make proper paths inside of zip archive, after I fixed the paths, all started just to work!

**Comment by alexeybolv** [comment]
> In my case it turned out that I needed to make proper paths inside of zip archive, after I fixed the paths, all started just to work!

Sorry, can you please provide some more info about problem with pathes?
I have the same issue here [https://github.com/CocoaPods/CocoaPods/issues/10671](url)

May be you can look through it and give me some suggestion?

**Comment by 6epreu** [comment]
@alexeybolv I did not solve this issue unfortunately and switched to Swift Package Manager. 
@Gray-Wind you were able to solve it, could you provide info how?

**Comment by alexeybolv** [comment]
> @alexeybolv I did not solve this issue unfortunately and switched to Swift Package Manager.
> @Gray-Wind you were able to solve it, could you provide info how?

I haven't got problems with SPM too.

**Comment by Gray-Wind** [comment]
I use the same zip archive for SPM distribution and for CocoaPods.
When you create zip archive, make sure you archive files, not a folder containing files, you can check archive with `unzip -l` make sure, your files have no leading folder.

**Comment by dnkoutso** [comment]
From the original authors post I am unable to reproduce. @6epreu maybe things have changed in the repo since the bug was filed?

I am getting a different issue when building UnitTestWithPodTests target:

```

Showing All Issues
Ignoring file /Users/dimitris/Development/ios/scrap/UnitTestRepo/UnitTestWithPod/UnitTestWithPod/ossl/lib/libssl.a, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64

Ignoring file /Users/dimitris/Development/ios/scrap/UnitTestRepo/UnitTestWithPod/UnitTestWithPod/ossl/lib/libcrypto.a, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64

Undefined symbol: _MD5
```

Please provide a specific branch and/or more details for us to diagnose further.

**Comment by dnkoutso** [comment]
moving out of 1.11 due to inactivity.

**Comment by abmomen** [comment]
I am having Kina same issue. I have created xcframework from command line xcodebuild. it works when I drag and drop it in a demo project but but does not work when adding from cocoa pod. 
Here is my pod spec which is hosted in a git repo 
Pod::Spec.new do |s|
    s.name              = 'ShareTripSDK'
    s.version           = '1.0.0'
    s.summary           = 'ST Spec'
    s.homepage          = 'https://www.sharetrip.net'
    s.source = { :http => 'https://github.com/abmomen/ShareTripSDK/releases/download/1.0.0/ShareTripSDK.xcframework.zip' }
    s.author            = { 'Abdul Momen' => 'abdulmomenict@gmail.com' }
    s.license = { :type => "MIT", :text => "MIT License" }

    s.platform     = :ios, "11.0"
    s.swift_version = "5.0"
    s.vendored_frameworks = 'ShareTripSDK.xcframework'
    
    s.dependency 'JWT'
    s.dependency 'PKHUD'
    s.dependency 'Base64'
    s.dependency 'Koloda'
    s.dependency 'BlueECC'
    s.dependency 'BlueRSA'
    s.dependency 'Alamofire'
    s.dependency 'lottie-ios'
    s.dependency 'SwiftyJSON'
    s.dependency 'Kingfisher'
    s.dependency 'Bolts-Swift'
    s.dependency 'BlueCryptor'
    s.dependency 'FloatingPanel'
    s.dependency 'GoogleSignIn'
    s.dependency 'ImageSlideshow'
    s.dependency 'JTAppleCalendar'
    s.dependency 'SwiftKeychainWrapper'
    s.dependency 'Socket.IO-Client-Swift'
    s.dependency 'FBSDKCoreKit'
    s.dependency 'FBSDKLoginKit'
    s.dependency 'FBSDKShareKit'
    s.dependency 'FirebaseAuth'
    s.dependency 'FirebaseFirestore'
    s.dependency 'FirebaseAnalytics'
    s.dependency 'FirebaseMessaging'
    s.dependency 'FirebaseCrashlytics'
    s.dependency 'FirebaseRemoteConfig'
    s.dependency 'FirebaseDynamicLinks'
    s.dependency 'IQKeyboardManagerSwift'
    s.dependency 'FirebaseCoreDiagnostics'
end

**Comment by osrufung** [comment]
That´s an issue we had during our CP to SPM migration process, we solved and documented here:
https://medium.com/p/96f225a12a20
