### ISSUE TITLE
Multiple commands produce an error when the framework has create directory command

### ISSUE THREAD

**Issue by hojideli** [CocoaPods/CocoaPods#10673]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Hello, 
We have used several different targets in the project, which have different iOS versions.
For example, 'MyApp1' requires a minimum iOS deployment target of 11. But other targets use 10.
Similar to the podfile below:

```
source 'http://...private pod spec repository....git'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

def shared_pods
      ...
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'lottie-ios'
  pod 'OneSignal'
      ...
end

target 'MyApp1' do
  platform :ios, '11.0'
  shared_pods
  
  # Payment
  pod 'Stripe'
  
end

target 'MyApp2' do
  platform :ios, '10.0'
  shared_pods
  
  # Data Analytics
  pod 'Firebase/Analytics'
  
end

# other targets for notification extensions
target 'MyApp1NotificationExtension' do
  platform :ios, '11.0'
  pod 'OneSignal'
end

target 'MyApp2NotificationExtension' do
  platform :ios, '10.0'
  pod 'OneSignal'
end

```

After we run 'pod install', it looks like the image below is displayed in the xcode:

<img width="494" alt="Screen Shot 2021-05-24 at 4 25 53 PM" src="https://user-images.githubusercontent.com/11157749/119344578-13a6e180-bcad-11eb-8c6a-106dcb200b4b.png">

There is no problem Build and Run apps on the device, But when we want to archive, we face a problem
```
Multiple commands produce '/Users/ ... /iphoneos/Alamofire.framework':
1) Target 'Alamofire-iOS10.0' has create directory command with output '/Users/ ... /iphoneos/Alamofire.framework'
2) Target 'Alamofire-iOS11.0' has create directory command with output '/Users/ ... /iphoneos/Alamofire.framework'
```

## What did you expect to happen?
It is possible to archive from any of the targets depending on the different iOS versions

## What happened instead?
As you seen in above note getting same error

## Stack
```
CocoaPods : 1.10.1
Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
RubyGems : 3.0.3
Host : Mac OS X 11.3 (Big sur)
Xcode: 12.5 (12E262)
Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
```

**Comment by mitasic995** [comment]
I'm having similar issue but I have two framework targets with different OS (tvOS, iOS). I'm using two separete aggregated targets with script in it to archive and create .xcframework for each framework. One works well but other is throwing this error:

```
Multiple commands produce '/Users/..../Build/Intermediates.noindex/ArchiveIntermediates/<PROJECT_NAME>-tvOS/InstallationBuildProductsLocation/Library/Frameworks/CryptoSwift.framework':
1) Target 'CryptoSwift-iOS' has create directory command with output '/Users/..../Build/Intermediates.noindex/ArchiveIntermediates/<PROJECT_NAME>-tvOS/InstallationBuildProductsLocation/Library/Frameworks/CryptoSwift.framework'
2) Target 'CryptoSwift-tvOS' has create directory command with output '/Users/..../Build/Intermediates.noindex/ArchiveIntermediates/<PROJECT_NAME>-tvOS/InstallationBuildProductsLocation/Library/Frameworks/CryptoSwift.framework'
```
And like this for **every** Cocoapods dependencies I have in workspace. 
It's weird for me why is this `'CryptoSwift-iOS' ` even trying to do something in `/<PROJECT_NAME>-tvOS/`, when I'm building (using cli command in script) the tvOS scheme? Script is containing only `xcodebuild archive ` and `xcodebuild -create-xcframework` commands.

Other aggregated target for iOS is working well, also building tvOS framework target from Xcode works well.

**Comment by dnkoutso** [comment]
This might be fixed by #10826 for 1.11.0

can someone verify or provide a sample app so I can verify?

**Comment by hojideli** [comment]
@dnkoutso Here is a sample app [Multiple commands produce error Test.zip]
[Test.zip](https://github.com/CocoaPods/CocoaPods/files/6950750/Test.zip)

This is show error
<img width="999" alt="Screen Shot 2021-08-08 at 5 57 29 PM" src="https://user-images.githubusercontent.com/11157749/128633649-e1aa8052-1ff5-40b8-9a0e-efae64157311.png">

**Comment by dnkoutso** [comment]
I was able to build all targets using Xcode 11 and CocoaPods master branch (which will be 1.11.0)!

I am going to close this issue as fixed by https://github.com/CocoaPods/CocoaPods/pull/10826

**Comment by dnkoutso** [comment]
Heres the archive of App1 on Xcode 12.1 and CocoaPods master (1.11.0)

<img width="1748" alt="Screen Shot 2021-08-08 at 9 11 35 PM" src="https://user-images.githubusercontent.com/310370/128641544-c42b5cdb-52d6-4818-9df3-cb983dd3da8c.png">
<img width="1112" alt="Screen Shot 2021-08-08 at 9 11 34 PM" src="https://user-images.githubusercontent.com/310370/128641548-9a6f45b1-9501-4df4-b215-f3ee42cadc29.png">

**Comment by marciogranzotto** [comment]
@dnkoutso like @wudijimao said this is still an issue. ( #10980 )

**Comment by dnkoutso** [comment]
We can continue discussion in #10980.

**Comment by dnkoutso** [comment]
I believe those are slightly different tbh. One has to do with subspecs this one did not. It had to do with different apps in a Podfile consuming the same pod with a different iOS version so its more about variants than subspecs.
