### ISSUE TITLE
M1 - Failed to load the test bundle, doesn’t contain a version for the current architecture.

### ISSUE THREAD

**Issue by omarzl** [CocoaPods/CocoaPods#10733]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

IMPORTANT! I am opening this issue to discuss if there is a possible solution from Cocoapods (I think it might be not possible, seems an Xcode bug), also to leave an example in case it helps someone, I am also including a workaround/solution to solve it.

## Setup

- Our app statically links the libraries so we are using `use_modular_headers!`
- This issue is only with M1, we can't compile yet to arm64 simulators so we are using x86_64 simulators, we set up the project with this setting `config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"` for the Pods and the App target to force it.

## What did you do?

We have a Pod that contains a test spec that **doesn't use app host**

## What did you expect to happen?

We expect that the pods, app and test bundles compile and run the tests.

## What happened instead?

Everything compiles but the test aren't running because it shows this error:

```
Test: xctest (82967) encountered an error in System Failures failed in Test Scheme Action on iPhone 12 Pro
  Assertions: System: Failed to load the test bundle. If you believe this error represents a bug, please attach the result bundle at /Users/omarzunigalagunas/Library/Developer/Xcode/DerivedData/DemoApp-ejmgmukqzhgszvbcrchncqbraier/Logs/Test/Test-DemoApp-2021.06.22_22-47-35--0500.xcresult. (Underlying Error: The bundle “DemoPod-Unit-DemoPodTests” couldn’t be loaded because it doesn’t contain a version for the current architecture. The bundle doesn’t contain a version for the current architecture. Try installing a universal version of the bundle. dlopen_preflight(/Users/omarzunigalagunas/Library/Developer/Xcode/DerivedData/DemoApp-ejmgmukqzhgszvbcrchncqbraier/Build/Products/Debug-iphonesimulator/DemoPod-Unit-DemoPodTests.xctest/DemoPod-Unit-DemoPodTests): no suitable image found.  Did find:
	/Users/omarzunigalagunas/Library/Developer/Xcode/DerivedData/DemoApp-ejmgmukqzhgszvbcrchncqbraier/Build/Products/Debug-iphonesimulator/DemoPod-Unit-DemoPodTests.xctest/DemoPod-Unit-DemoPodTests: mach-o, but wrong architecture)

```
The app compiles and it runs in x86_64 simulators but the test bundle fails to run because some Xcode process is running under arm64 and can't load the test bundle.

This issue can be solved by setting up the test spec to use an app host: `requires_app_host = true`, this way Xcode launches an x86_64 simulator to install the app host and that way it can load the x86_64 compiled test bundle.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.7p197 (2021-04-05 revision 67941) [arm64-darwin20]
    RubyGems : 3.0.3.1
        Host : macOS 11.4 (20F71)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /opt/homebrew/Cellar/ruby@2.6/2.6.7/lib
Repositories : bitbucket-podspecs - git - git@bitbucket.org:rappinc/podspecs.git @ 09214c4a326633972dbd0d9642ae30c522d795bd

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/lib/ruby/gems/2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '14.4'
use_modular_headers!

target 'DemoApp' do
  pod 'DemoPod', :path => '.', :testspecs => ['DemoPodTests']

  target 'DemoAppTests' do
    inherit! :search_paths
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
```

## Project that demonstrates the issue

[unit-test-error.zip](https://github.com/CocoaPods/CocoaPods/files/6698852/unit-test-error.zip)

- By executing CMD+U the issue will show up
- By uncommenting line 15 in DemoPod.podspec + pod install, the issue will disappear and the test will run

**Comment by dnkoutso** [comment]
Thanks for the issue filing! I do not have an M1 unfortunately to debug and diagnose.

**Comment by dnkoutso** [comment]
@omarzl its possible this is fixed with https://github.com/CocoaPods/CocoaPods/pull/10830 but not entirely sure.

I do not have an M1 to test it out.

**Comment by freddi-kit** [comment]
If this is already included in the 1.11.0.beta.2, i confirmed it has not fixed yet with M1 with this version.

**Comment by dnkoutso** [comment]
yeap it did. This was a long shot anyway. I do not have an M1 to be able to diagnose and fix this issue.

**Comment by nysander** [comment]
same here

**Comment by ninokierulf** [comment]
issue still exists in `1.11.2`, `requires_app_host = true` works but is slow if there are multiple test targets (multiple dev pods)

**Comment by zeeshankhan** [comment]
Hello there,
I'm still facing this or tests not being included when running Xcode using Rosetta.
- I'm using the latest version of Cocoapods
- I excluded the arm64 architecture.
- I installed `sudo gem install ffi` by using Terminal with Rosetta
- I also reinstalled Cocoapods after that.
- I also tried `requires_app_host = true` 

but nothing seems to be working for me.
Unless I run Xcode in Rosetta, it `Failed to load the test bundle`.
and with Rosetta I get 0 test executed.

All of my test files are checked in the target but it still does not test a single file.
Please let me know if we have any solution here.
Thanks a lot.

**Comment by zeeshankhan** [comment]
Hey guys,
The pattern I'm seeing in my code is that when I add `requires_app_host = true` it does not include any test in the app host.
<img width="718" alt="Screen Shot 2022-02-25 at 9 09 27 AM" src="https://user-images.githubusercontent.com/373262/155657541-b1363a1f-8d28-4605-abdf-eac7843be8da.png">


And when I do not add the app host requirement it fails to load the test bundle.
<img width="645" alt="Screen Shot 2022-02-25 at 9 10 32 AM" src="https://user-images.githubusercontent.com/373262/155657639-1a7977ce-66b1-46d9-b8ce-9f3d33510326.png">

Please let me know if you have any ideas. Any help here is greatly appreciated.
Thank you.

**Comment by CyrilCermak** [comment]
Hi all,

I am working in a highly modular framework with tons of modules. What worked for me was to run the tests directly on the Mac. There I don't need to have the app target for those tests... I hope this workaround will help someone as for me it is a much better solution than having a dedicated app for each module.

Thanks!
<img width="323" alt="Screenshot 2023-02-01 at 16 57 37" src="https://user-images.githubusercontent.com/13216787/216095195-ace13788-51ac-4bd1-a4e0-c71bb1348206.png">

**Comment by xiaojin** [comment]
I solved it by using this way
[https://stackoverflow.com/questions/73799488/failed-to-load-test-bundle-on-mac-m1-found-x86-64-required-arm64/75894979#75894979](StackOverflow)

**Comment by tienanhtran98** [comment]
run xcode with rosetta , will resolve this problem
