### ISSUE TITLE
Error with `pod update`

### ISSUE THREAD

**Issue by n-insaidoo** [CocoaPods/CocoaPods#10930]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod update`

## What did you expect to happen?

Update all the pods correctly. Is there a reason why the permission bits of my `.netrc` file should be specifically `0600` when carrying this operation?

## What happened instead?

Was given an error concerning `.netrc` permission bits

```
Update all pods
  Preparing

Updating local specs repositories
[!] Couldn't determine repo type for URL: `https://cocoapods-cdn.netlify.app/`: Permission bits for '/home/xxx/.netrc' should be 0600, but are 644

/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:89:in `rescue in cdn_url?'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:73:in `cdn_url?'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:37:in `create_source_with_url'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:22:in `find_or_create_source_with_url'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:177:in `map'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:237:in `block in resolve_dependencies'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:236:in `resolve_dependencies'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:161:in `install!'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/command/update.rb:63:in `run'
/usr/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
/usr/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

```

### Stack

```
   CocoaPods : 1.11.0
        Ruby : ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]
    RubyGems : 3.1.6
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : xcodebuild) ()
         Git : git version 2.26.3
Ruby lib dir : /usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# see CDN issue https://github.com/CocoaPods/CocoaPods/issues/9270
source 'https://cocoapods-cdn.netlify.app/'

target 'Swipeless' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swipeless
  pod 'Alamofire', '~> 4.4'
  pod 'BigInt'
  pod 'KeychainSwift'
  pod 'MBProgressHUD'
  pod 'OmiseGO'
  pod 'SipHash'
  pod 'SkyFloatingLabelTextField'
  pod 'Starscream'
  pod 'Toaster'

  target 'SwipelessTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by dnkoutso** [comment]
This is fixed by https://github.com/CocoaPods/Core/pull/703 which will ship with 1.11.1.

I tried your repo URL with the fix and it seems to pass so I am going to close for now. We are looking to ship 1.11.1 this week hopefully.

You may use the `1-11-stable` branch if you use Bundler or switch back temporarily to 1.10.2.

**Comment by n-insaidoo** [comment]
@dnkoutso That's great news, thank you!

**Comment by bofeizhu** [comment]
Hi @dnkoutso, I'm still getting this error with both 1.11.1 & 1.11.2.

**Comment by dnkoutso** [comment]
Please file a new issue specify the repo that does not work for you. It might be a new regex update we need on https://github.com/CocoaPods/Core/pull/703

**Comment by bofeizhu** [comment]
@dnkoutso I filed #10963.
