### ISSUE TITLE
Process *.lproj/*.strings in resource_bundle.

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaPods/CocoaPods#1653]
My library resources are localized and I'm using `resource_bundle` include them along nibs and images.

* If I specify:  
`s.resource_bundle = { 'MyResources' => 'Resources/*.{png,xib,strings}' }`  
String files are they are processed (resulting *.strings are binary, which is both good for performance and space while also *concealing contents*), but they don't preserve their *.lproj directories and breaks localization (similar to #846).

* On the other my current workaround:  
`s.resource_bundle = { 'MyResources' => 'Resources/*.{png,xib,lproj}' }`  
Preserves the *.lproj directories (as in #807) and internationalization works, but then string files are not processed, so they are bigger and less performant.

It would be really nice to have both internationalization work and string files processing.

**Comment by brianpartridge** [comment]
This is biting me right now with xibs as well as strings within an lproj directory.  I've tried:

      s.resource_bundle = { "MyResources" => ["Resources/*.lproj/*.{xib,strings}"] }
      s.preserve_paths = "Resources/*.lproj"

But it results in a single nib and strings file in the resource bundle, rather than nib and strings files in a localized directory.  Are there any known workarounds?

**Comment by ehuynh** [comment]
@brianpartridge I have some success with just including the directory. So if you have something like
```
s.resource_bundle = { "MyResources" => ["Resources/*"] }
```
By doing this, cocoapods would just copy everything in the directory *as in* without flatten the directory. Now you might have other files in there you don't want to copy over, in that case I suggest you create another folder under Resources (e.g. Resources/Localization) and then just have something like 
```
s.resource_bundle = { "MyResources" => ["Resources/Localization*"] }
```

**Comment by bretongoers** [comment]
Curious if there is a solution in place that works 100% of the time? We have a `xib` file to ship with our pod that has been localized. The xib sits under `Base.lproj`, and then translations sit under `<lang>.lproj` folders in `<lang>.strings` files. We have been unable to get the pod to work using:
  ```
s.resource_bundle = {
    'PodResources' => ['Pod/Resources/**/*.*'],
    'PodResources-Localizations' => ['Pod/Localizations/*.lproj']
}
```
The error occurs because the localizations bundle can't find the `xib`. It's copied over under the `Base.lproj` directory, but when we use `loadNibNamed...` with the `PodResources-Localizations` bundle to load it up, it crashes. How do we get the pod to find the `xib` while also preserving the localizations? Is it not supposed to sit under the `Base.lproj`?

**Comment by mrtj** [comment]
Any updates on this? Are there any way to put localizable strings to a cocoapod podspec in a way that it would work?

**Comment by dnkoutso** [comment]
Same here bitten by this and unable to find a solid solution.

**Comment by efirestone** [comment]
This should be resolved in 1.0.0.beta.1

**Comment by linlin5910** [comment]
I'm still stuck with it.
I refer to the demo [https://github.com/dlinsin/cocoapods-storyboard-sample](url) and use 
  s.resource_bundles = {
    'Resources' => ['LocalizationDemo/LocalizationDemo/Resources/**/*.{lproj,storyboard}']
  }
but the directories  result is
-Resources
--en.lproj
---LocalizationDemo.strings
--LocalizationDemo.storyboard
--de.lproj
---LocalizationDemo.strings
my cocoapods version is 1.0.1 but the result seem not conform to the changes
> Special case interface files to use the XIB or Storyboard name for the variant group when using Base Internationalization.
cloud anyone show me a correct usage or demo？

**Comment by abbeycode** [comment]
@linlin5910 Have you gotten something to work yet? I'm still finding that when my app calls code that uses a localization inside my Pod library, that the string still isn't localized. I'm using the format that @efirestone recommended:

```
  s.resource_bundles = {
      'UnzipKit' => ['Resources/**/*']
  }
```

On disk I have this:

```
- Resources
-- base.lproj
--- Localizable.strings
```

What I end up with in the generated Pods project is this (I'm installing from a local path until I get the kinks worked out):

```
- Development Pods
-- UnzipKit
--- Resources
---- Resources
----- Localizable.strings
```

I'm running my host app with the "Show non-localized strings" build setting, and when one of the strings appears in a dialog box, it's all caps, indicating it isn't localized.

**Comment by abbeycode** [comment]
@efirestone I also tried using just `resources` instead of `resource_bundles` and that didn't make a difference either.

**Comment by abbeycode** [comment]
I figured it out. I needed to update my CocoaPods code to use a strings table named something other than Localizable (since it was colliding with my app's Localizable.string file) and use `NSLocalizedStringFromTable`, giving that name.

**Comment by linlin5910** [comment]
My interface internationalization problem had been solved.But the directories are still strange.
On disk I have this:
```
-Resources
--xibs
---Base.lproj
----MyView.xib
---en.lproj
----MyView.strings
```
and it on xcode like:
```
-Resources
--xibs
---MyView.xib
----MyView.xib(Base)
----MyView.string(English)
```
then i use
```
  s.resource_bundles = {
    'Resources' => ['MyProject/Resources/**/*']
  }
```
after pod update the directories result on xcode like this
```
-Resources
--MyView.xib
---MyView.xib(Base)
---MyView.string(English)
--xibs
---Base.lproj
----MyView.xib
---en.lproj
----MyView.strings
```
shouldn't it only show a variant group name MyView.xib instead of show the .lproj file direct?
