### ISSUE TITLE
[Frameworks] Archive to .ipa not functional (iOS)

### ISSUE THREAD

**Issue by flovilmart** [CocoaPods/CocoaPods#2871]
Upon archiving a project with pods as frameworks, the pods frameworks are only symlinked into the archive and not fully copied over there

![capture d ecran 2014-11-24 a 17 07 05](https://cloud.githubusercontent.com/assets/364568/5174175/dea6c356-73fc-11e4-920c-55dc4dac308f.png)

Here is a screen shot of what the app.ipa/Frameworks folder look like after archiving.

As you can see, Alamofire has been build as Target dependency / Copy Framework and is properly copied (not POD)

The pod frameworks, Analytics and Intercom are symlinked to 

Bibliothèque ▸ Developer ▸ Xcode ▸ DerivedData ▸ XXXX-fyebndqcoxbdhuchgoekcvtteixi ▸ Build ▸ Intermediates ▸ ArchiveIntermediates ▸ XXXX-Dev ▸ IntermediateBuildFilesPath ▸ UninstalledProducts

That prevents proper OTA deployment

**Comment by XBeg9** [comment]
Again reproduced in latest 0.36b... fixed temporary via https://www.bountysource.com/issues/7505475-swift-pod-causes-runtime-failure-in-obj-c-host-app-on-device-codesign-issue
Something removed in 0.36b ? @mrackwitz 

![keyboard-ios zsh 2015-01-26 23-16-47](https://cloud.githubusercontent.com/assets/872907/5908558/6dd4673c-a5b1-11e4-8534-d26588ccc740.jpg)

**Comment by neonichu** [comment]
@XBeg9 the issue you've linked to was fixed in #3009, after 0.36 beta was released.

**Comment by XBeg9** [comment]
@neonichu Don't know what you mean with ObjC host app. It's Swift app with bridge header to support some 3rd party libraries via Cocoapods. That's all. I am still facing problems even with such installation:
`gem 'cocoapods', :github => 'CocoaPods/CocoaPods'`

**Comment by Morji** [comment]
I'm facing the same issue. I've included a Swift framework among my 3 Obj-C ones which caused all of them to be build as Frameworks now. I am running 0.36.0.beta2 but all 3 Frameworks are symlinked and not placed in the final .ipa archive. Any workarounds or upcoming changes?

**Comment by neonichu** [comment]
@Morji could your issue be spaces in paths somehow? See #3125

**Comment by Morji** [comment]
Yes actually, my project has spaces in the name.... I guess I'll just rename it. Thanks :)

**Comment by neonichu** [comment]
Thanks for confirming, it'll be fixed in the next release.
