### ISSUE TITLE
podspec option ignored in favor of "CHECKOUT OPTIONS"?

### ISSUE THREAD

**Issue by joenoon** [CocoaPods/CocoaPods#2890]
It looks like the :podspec option is being ignored in favor of the "CHECKOUT OPTIONS" from the lockfile.  However when the project is downloaded, there is no podspec in its root, which is why I'm trying to give it one.  I'm interacting with cocoapods through rubymotion.

Podfile:
========
```
pod 'LogEntries', :podspec => 'podspecs/LogEntries.podspec'
```
 
podspecs/LogEntries.podspec:
========
``` 
Pod::Spec.new do |s|
  s.name         =  'LogEntries'
  s.version      =  '0.0.2'
  s.summary      =  'LogEntries iOS SDK'
  s.homepage     =  'https://github.com/logentries/le_ios'
  s.author       =  { 'LogEntries Support' => 'support@logentries.com' }
  s.source       =  { :git => 'https://github.com/logentries/le_ios.git' }
  s.source_files =  'lelib/*.{h,m}'
  s.prefix_header_file = 'lelib/lelib-Prefix.pch'
  s.ios.deployment_target = '6.0'
  s.requires_arc = true
end
```
Podfile.lock:
========
``` 
PODS:
  - LogEntries (0.0.2)
 
DEPENDENCIES:
  - LogEntries (from `podspecs/LogEntries.podspec`)
 
EXTERNAL SOURCES:
  LogEntries:
    :podspec: podspecs/LogEntries.podspec
 
CHECKOUT OPTIONS:
  LogEntries:
    :commit: dcd211287b85c0238c7b7b49fe1ee92f58a224d0
    :git: https://github.com/logentries/le_ios.git
 
SPEC CHECKSUMS:
  LogEntries: c31cf7b0c7f3aca8d77e687c7176079ea08a92bc
 
COCOAPODS: 0.35.0
```
 
Output:
========
 
 
```
Pre-downloading: `LogEntries` from `https://github.com/logentries/le_ios.git`, commit `dcd211287b85c0238c7b7b49fe1ee92f58a224d0`
rake aborted!
[!] No podspec found for `LogEntries` in vendor/Pods/LogEntries/LogEntries.podspec.json
```

**Comment by joenoon** [comment]
This still seems to be the case as of 0.36.0.beta.2. I'm pinned to 0.34.4 which seems to be the last version that the :podspec option worked.  Is there any known workaround?

**Comment by segiddins** [comment]
@joenoon could you check if this is perchance fixed in 0.36.3?

**Comment by joenoon** [comment]
@segiddins unfortunately not.  I updated cocoapods on https://github.com/joenoon/cocoapods-test-1 and it still reproduces the problem.

**Comment by segiddins** [comment]
Whenever I try and run this, all I get is `ERROR! The requested deployment target SDK is not available or supported by RubyMotion at this time.`

**Comment by segiddins** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
