### ISSUE TITLE
Duplicate pods when using source

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#3365]
I want to use a specific fork of `SocketRocket` on GitHub, but found that it's been included twice.

I think this could be because I've got a set up that involves a `MyProj` target linking with a `MyProjKit` pod, and there are just some transitive dependencies that mess things up.  Just to be clear:

```
# Podfile
  ...
target 'MyProj' do
  pod 'SocketRocket', :git => 'https://github.com/quatanium/SocketRocket'
  pod 'MyProjKit', :path => '../MyProjKit'
  ...
end
```

And in `MyProjKit.podspec` I depend on `libPusher` — a project that depends on `SocketRocket`.

```
# MyProjKit.podspec
...
    ss.dependency 'libPusher'
    ss.dependency 'libPusher/ReactiveExtensions'
```

After I `pod install` on `MyProj`,  it produces the following `Podfile.lock` file. I've omitted everything but the interesting parts:

```
# Podfile.lock
PODS:
  ...
  - libPusher/Core (1.6):
    - SocketRocket (= 0.3.1-beta2)
  ...
  - SocketRocket (0.3.1-beta2)
DEPENDENCIES:
  - SocketRocket (from `https://github.com/quatanium/SocketRocket`)
EXTERNAL SOURCES:
   ...
  SocketRocket:
    :git: https://github.com/quatanium/SocketRocket
CHECKOUT OPTIONS:
  ...
  SocketRocket:
    :commit: 169eb0e9fbfd91cd45dff115a49c462ace1c74e3
    :git: https://github.com/quatanium/SocketRocket

SPEC CHECKSUMS:
  SocketRocket: 70df1983148525857ced17c57207bfb939bc6b8e
```

I don't know whether this looks wrong in any way or not.

What I can tell you is, when I compile my project I get these warnings:

```
Class SRWebSocket is implemented in both <<LONG PATH>> and <<LONG PATH>>. One of the two will be used. Which one is undefined.
Class SRIOConsumer is implemented in both <<LONG PATH>> and <<LONG PATH>>. One of the two will be used. Which one is undefined.
Class SRIOConsumerPool is implemented in both <<LONG PATH>> and <<LONG PATH>>. One of the two will be used. Which one is undefined.
Class _SRRunLoopThread is implemented in both <<LONG PATH>> and <<LONG PATH>>. One of the two will be used. Which one is undefined.
```

How do I get rid of the warnings?

**EDIT**:  I'm using Cococapods version `0.36.3`

**Comment by bitomule** [comment]
I've the same issue, any update on this?

**Comment by segiddins** [comment]
Can you please provide a reproducible example of the issue ?

**Comment by bitomule** [comment]
I think it was an issue with xcode 6.1 and 6.3.1 fixed it The error never appeared again since the update.

**Comment by fatuhoku** [comment]
@bitomule I'm now running Cocoapods `0.37.2` and Xcode `6.3.2` and I'm still getting the same issue.

**Comment by neonichu** [comment]
This issue should be solved once #3550 is merged, there will only be one target for SocketRocket then.

**Comment by fatuhoku** [comment]
@neonichu :beers: can't wait to get those ugly warnings from my trace!

**Comment by fatuhoku** [comment]
@neonichu I'm using Cocoapods `0.38.2` and I'm still experiencing this issue. What might be up?

**Comment by neonichu** [comment]
@fatuhoku not sure, can you post an example in which this is happening?
