### ISSUE TITLE
0.37.0 "ENOENT - No such file or directory ... resources" (0.36.4 works)

### ISSUE THREAD

**Issue by jakubknejzlik** [CocoaPods/CocoaPods#3487]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

Installing pods on new project.

* What did you expect to happen?

Get successfully installed all pods. As in 0.36.0 where everything works ok.

* What happened instead?

Following error happened. Don't know if the problem is general or just in this pod (OneSignal pod is doing the same thing).

### Stack

```
   CocoaPods : 0.37.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a8dd4355a62502417592947258f3158593df0e32
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'cocoapods-fail-test' do
pod 'GameThrivePushNotifications', '~> 1.7'
end

target 'cocoapods-fail-testTests' do

end
```

### Error

```
Errno::ENOENT - No such file or directory - /<project_source>/Pods/GameThrivePushNotifications/iOS_SDK/Framework/GameThrive.framework/Resources
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/pod_source_installer.rb:107:in `chmod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/pod_source_installer.rb:107:in `block in lock_files!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/pod_source_installer.rb:105:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/pod_source_installer.rb:105:in `lock_files!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/pod_source_installer.rb:47:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:304:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:279:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:278:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:270:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:270:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:122:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:120:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:92:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by kylef** [comment]
This was fixed by #3515 and is in CocoaPods 0.37.1.

**Comment by oferRounds** [comment]
@kylef, I'm still facing this issue. This is my error log:

### Error

```
Errno::EEXIST - File exists - /Users/ofermoragbrin/Desktop/DatingApp/Pods/Target Support Files/Pods-DatingApp-ZLSwipeableView
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer.rb:86:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer.rb:86:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer.rb:86:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:19:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:508:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:505:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:505:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:504:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:132:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:129:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:97:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by oferRounds** [comment]
version 0.37.1
