### ISSUE TITLE
[0.37.0] Framework executable permissions are incorrect 

### ISSUE THREAD

**Issue by jonmaier** [CocoaPods/CocoaPods#3501]
Regression in 0.37, everything works fine under 0.36.4.
The permissions for _CrashlyticsFramework_ are incorrect and the build fails with

```
...ommitted../ios-build/build/App.build/Automation-iphoneos/AppTarget.build/Script-awesome.sh: line 3: ./Pods/CrashlyticsFramework/Crashlytics.framework/run: Permission denied
```

```
~/workspace/ios-build/Pods/CrashlyticsFramework/Crashlytics.framework $ l
total 1336
drwxr-xr-x  9 jenkins  _assetcache     306 May  4 16:48 .
drwxr-xr-x  5 jenkins  _assetcache     170 May  4 16:48 ..
lrwxr-xr-x  1 jenkins  _assetcache      28 May  4 16:48 Crashlytics -> Versions/Current/Crashlytics
lrwxr-xr-x  1 jenkins  _assetcache      24 May  4 16:48 Headers -> Versions/Current/Headers
drwxr-xr-x  3 jenkins  _assetcache     102 May  4 16:48 Modules
lrwxr-xr-x  1 jenkins  _assetcache      26 May  4 16:48 Resources -> Versions/Current/Resources
drwxr-xr-x  4 jenkins  _assetcache     136 May  4 16:48 Versions
-r--r--r--  1 jenkins  _assetcache  253984 May  4 16:48 run
-r--r--r--  1 jenkins  _assetcache  412960 May  4 16:48 submit
```

**Comment by segiddins** [comment]
\c @mglidden

**Comment by dbarden** [comment]
Fixes #3513

**Comment by kylef** [comment]
This was also fixed by #3506.

**Comment by segiddins** [comment]
No I don't think it was?

-Samuel E. Giddins

On May 6, 2015, at 2:19 AM, Kyle Fuller <notifications@github.com> wrote:

This was also fixed by #3506.

**Comment by dbarden** [comment]
No, it doesn't fix.
On #3506 the executable permission will still be removed.
