### ISSUE TITLE
error: You don’t have permission to save the file “Info.plist” in the folder “Resources”

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#3638]
0.37.2

`$ pod lint spec`
ends with this error. I don;t know what is going on, so here I am asking for help.

```
ProcessInfoPlistFile /var/folders/jj/yx6tw7ps52s9w3gh6nyrvzcr0000gn/T/CocoaPods/Lint/build/Release/Pods/CryptoSwift.framework/Versions/A/Resources/Info.plist Target\ Support\ Files/Pods-CryptoSwift/Info.plist
    cd /var/folders/jj/yx6tw7ps52s9w3gh6nyrvzcr0000gn/T/CocoaPods/Lint/Pods
    builtin-infoPlistUtility /var/folders/jj/yx6tw7ps52s9w3gh6nyrvzcr0000gn/T/CocoaPods/Lint/Pods/Target\ Support\ Files/Pods-CryptoSwift/Info.plist -expandbuildsettings -platform macosx -o /var/folders/jj/yx6tw7ps52s9w3gh6nyrvzcr0000gn/T/CocoaPods/Lint/build/Release/Pods/CryptoSwift.framework/Versions/A/Resources/Info.plist
error: You don’t have permission to save the file “Info.plist” in the folder “Resources”.

** BUILD FAILED **

The following build commands failed:
	ProcessInfoPlistFile /var/folders/jj/yx6tw7ps52s9w3gh6nyrvzcr0000gn/T/CocoaPods/Lint/build/Release/Pods/CryptoSwift.framework/Versions/A/Resources/Info.plist Target\ Support\ Files/Pods-CryptoSwift/Info.plist
(1 failure)
 -> CryptoSwift (0.0.11)
    - ERROR | [OSX] Returned an unsuccessful exit code.
    - NOTE  | [OSX]  error: You don’t have permission to save the file “Info.plist” in the folder “Resources”.

Analyzed 1 podspec.
```

**Comment by segiddins** [comment]
@mglidden is this another `chmod` issue?

**Comment by mglidden** [comment]
Potentially, although I'm not sure what's trying to edit the plist file.

I'll submit a patch for the chmod issue tonight and will update this ticket if I find anything relevant.

**Comment by segiddins** [comment]
:+1: thanks!

**Comment by mglidden** [comment]
I verified that this is caused by the locking, but didn't have time to fix it in #3640. I'll take a closer look tomorrow

**Comment by Aahung** [comment]
I cannot build now, do you have any progress?

**Comment by hamchapman** [comment]
I'm hitting this issue as well. I can provide more information if anyone wants it

**Comment by hamchapman** [comment]
My error is coming when trying to lint a pod spec for a pod that includes [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) by @krzyzanowskim, the creator of the issue. 

Perhaps there's a link between the fact that this error is happening for you @krzyzanowskim and when I'm using CryptoSwift rather than there being an actual issue with the cocoapods gem?

**Comment by krzyzanowskim** [comment]
@orta said once it should be trivial to fix, if you have any experience to cocoapods development it would be very helpful.

**Comment by orta** [comment]
Should be fixed by https://github.com/CocoaPods/CocoaPods/pull/3640

**Comment by hamchapman** [comment]
I've tried using #3640 to run `pod spec lint` and I'm still getting the same error unfortunately.

**Comment by segiddins** [comment]
@hamchapman that's because that PR isn't finished yet

**Comment by krzyzanowskim** [comment]
I tried with 0.38.2 and it's not working. Does is suppose to be working with this version?

**Comment by krzyzanowskim** [comment]
it passes `pod lib lint` though

$ pod lib lint
 -> CryptoSwift (0.0.11)
CryptoSwift passed validation.

**Comment by krzyzanowskim** [comment]
It that help, it happening to me only with :osx target. It is fine with :ios

**Comment by siuying** [comment]
Got same problem, do you need a sample project to reproduce the problem?

**Comment by krzyzanowskim** [comment]
This is how I finally handled this issue:

```
s.source_files  = "CryptoSwift/*"
```

changed it to

```
s.source_files  = "CryptoSwift/*.swift"
```

there was `Info.plist` file inside that was picked and this caused the trouble. It was not in the past, but it is with the current version. As a solution may be update search pattern for source_files to exclude some files, especially `Info.plist` that seems be copied with another rule.

**Comment by siuying** [comment]
@krzyzanowskim thanks!

**Comment by segiddins** [comment]
The source locking has been fixed.
