### ISSUE TITLE
Archiving not working in Xcode 7

### ISSUE THREAD

**Issue by danielnordh** [CocoaPods/CocoaPods#3798]
An app that builds and archives fine in Xcode 6.4, and builds to device in Xcode 7 is unable to be archived. Fails with the following message:

```
Run custom shell script 'Copy Pods Resources'
PhaseScriptExecution Copy\ Pods\ Resources /Users/Daniel/Library/Developer/Xcode/DerivedData/Curator-fppjaspuvfpqzidgmfkjwqzvrsdy/Build/Intermediates/ArchiveIntermediates/Curator\ (Live)/IntermediateBuildFilesPath/Curator.build/Release-iphoneos/curator-share.build/Script-1913A7E7DBF41C79836F5B0E.sh
    cd /Users/Daniel/Curator/Code/curator
    /bin/sh -c \"/Users/Daniel/Library/Developer/Xcode/DerivedData/Curator-fppjaspuvfpqzidgmfkjwqzvrsdy/Build/Intermediates/ArchiveIntermediates/Curator\ (Live)/IntermediateBuildFilesPath/Curator.build/Release-iphoneos/curator-share.build/Script-1913A7E7DBF41C79836F5B0E.sh\"

building file list ... done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
building file list ... done
rsync: push_dir#3 "/Users/Daniel/Library/Developer/Xcode/DerivedData/Curator-fppjaspuvfpqzidgmfkjwqzvrsdy/Build/Intermediates/ArchiveIntermediates/Curator (Live)/InstallationBuildProductsLocation" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-45/rsync/main.c(580) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]
Command /bin/sh failed with exit code 12
```

Pod file:

```ruby
    platform :ios, '8.0'
    def share_extension_pods
      pod 'CrashlyticsFramework', '~> 2.2'
    end

    def app_pods
      pod 'CrashlyticsFramework', '~> 2.2'
      # other pods
    end

    target 'curator-share' do
      share_extension_pods
    end

    target 'Curator' do
      app_pods
    end
```

Using CocoaPods 0.37.2 but also trying with 0.38, same issue.

**Comment by snakamura** [comment]
I have the same issue and applied this patch to Pods-<ProjectName>-resources.sh as a workaround.

```
--- Pods-Sample-resources.sh.orig  2015-07-09 15:54:54.000000000 +0900
+++ Pods-Sample-resources.sh   2015-07-09 15:36:10.000000000 +0900
@@ -60,6 +60,7 @@
 
 rsync -avr --copy-links --no-relative --exclude '*/.svn/*' --files-from="$RESOURCES_TO_COPY" / "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
 if [[ "${ACTION}" == "install" ]]; then
+  mkdir -p "${INSTALL_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
   rsync -avr --copy-links --no-relative --exclude '*/.svn/*' --files-from="$RESOURCES_TO_COPY" / "${INSTALL_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
 fi
 rm -f "$RESOURCES_TO_COPY"
```

**Comment by danielnordh** [comment]
Thanks @snakamura, unfortunately that didn't fix the issue for me. Same error.
Did you do anything else, did you edit the script before/after: pod install, archiving?

**Comment by kylef** [comment]
This should be fixed by #3675 in 0.38, can you please test again using the CocoaPods 0.38 releases?

**Comment by danielnordh** [comment]
Just tried again with 0.38.0.beta.2 but it does not solve the issue.
Error remains the same.

Looking at the message a bit closer I notice part of the Path differs in the two listings:
/Curator\ (Live)/ vs. /Curator (Live)/

It works fine in 6.4 though (with 0.37.2)

**Comment by segiddins** [comment]
@danielnordh please post a pod file we can sue to reproduce?

**Comment by danielnordh** [comment]
Sure, here's the Podfile:

    platform :ios, '8.0'

    # ignore all warnings from all pods
    inhibit_all_warnings!
    
    def share_extension_pods
      pod 'CrashlyticsFramework', '~> 2.2'
    end
    
    def app_pods
    
      #pod [Private Local Pod]
      #pod [Private Local Pod]
      pod 'Harpy', '~> 2.6'
      pod 'CrashlyticsFramework', '~> 2.2'
      pod 'PSAlertView', '~> 2.0'
      pod 'SVProgressHUD', :git => 'https://github.com/TransitApp/SVProgressHUD.git'
      pod 'AFNetworkActivityLogger', '~> 2.0'
      pod 'FormatterKit', '~> 1.7'
      pod 'ParseFacebookUtils', '~> 1.4'
      pod 'Mixpanel', '~> 2.5'
      pod 'UIImageViewAligned', :git => 'https://github.com/reydanro/UIImageViewAligned.git'
      pod 'RMStore/AppReceiptVerificator', '~> 0.6'
      pod 'KVOController', '~> 1.0'
      pod 'TransitionKit', '~> 2.0.0'
      pod 'GoogleAnalytics'
      pod 'AMPopTip'
      pod 'Optimizely-iOS-SDK'
      pod 'LogglyLogger-CocoaLumberjack'
      
      # Remove unsupported localisations from FormatterKit
      prepare_command = <<-CMD
      SUPPORTED_LOCALES="['base', 'en']"
      find . -type d ! -name "*$SUPPORTED_LOCALES.lproj" | grep .lproj | xargs rm -rf
      CMD
    
    end
    
    # don't use any pods for the share extensions
    target 'curator-share' do
      share_extension_pods
    end
    
    target 'curator-share-test' do
      share_extension_pods
    end
    
    target 'Curator' do
      app_pods
    end
    
    target 'CuratorTest' do
      app_pods
    end


Perhaps worth noting as well that the error is related to our Share Extension Target, not the main app.
The following warnings are also presented when trying to archive:

    warning: (armv7) /Users/Daniel/Library/Developer/Xcode/DerivedData/Curator-fppjaspuvfpqzidgmfkjwqzvrsdy/Build/Intermediates/ArchiveIntermediates/Curator (Live)/BuildProductsPath/Release-iphoneos/libPods-curator-share.a(Pods-curator-share-dummy.o) unable to open object file: No such file or directory
    warning: (arm64) /Users/Daniel/Library/Developer/Xcode/DerivedData/Curator-fppjaspuvfpqzidgmfkjwqzvrsdy/Build/Intermediates/ArchiveIntermediates/Curator (Live)/BuildProductsPath/Release-iphoneos/libPods-curator-share.a(Pods-curator-share-dummy.o) unable to open object file: No such file or directory

**Comment by danielnordh** [comment]
App archives successfully in Xcode 7 and 0.37.2 if I remove the Share Extension from the app's Embedded Binaries.

**Comment by segiddins** [comment]
@danielnordh can you check if https://github.com/CocoaPods/CocoaPods/pull/3820 fixes things for you?

**Comment by skydivedan** [comment]
I'm having this problem in 0.37.2, too, and I can't remove my extensions from my app. I'll be looking at 0.38 soon, to see if it remedies the issue. I'm pretty sure that I don't need this build step for my extension (unless I'm misunderstanding what this build step does). Is there a way I can change my podfile, so that this build-step doesn't get generated in the first place?

**Comment by segiddins** [comment]
@skydivedan this is presumably fixed in 0.38.2

**Comment by dmathewwws** [comment]
I do not think this is solved.

I'm running into a very similar issue:

Error:
````
Run custom shell script 'Copy Pods Resources'

PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/dmathewwws/Library/Developer/Xcode/DerivedData/PhotoTaggr-haohxccqhbnuxsegptinnqxvzyxz/Build/Intermediates/ArchiveIntermediates/PhotoTaggr/IntermediateBuildFilesPath/PhotoTaggr.build/Release-iphoneos/PhotoTaggrShare.build/Script-6841889167BD98E9473F5449.sh
 
building file list ... done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
building file list ... done
rsync: push_dir#3 "/Users/dmathewwws/Library/Developer/Xcode/DerivedData/PhotoTaggr-haohxccqhbnuxsegptinnqxvzyxz/Build/Intermediates/ArchiveIntermediates/PhotoTaggr/InstallationBuildProductsLocation" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(580) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]
Command /bin/sh failed with exit code 12
````

Podfile:
````
platform :ios, '8.0'
use_frameworks!
link_with 'PhotoTaggr', 'PhotoTaggrShare'

target 'PhotoTaggr' do
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'Parse'
end

target 'PhotoTaggrShare' do
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
end
````

Copy Pod Resources
````
Shell: /bin/sh
"${SRCROOT}/Pods/Target Support Files/Pods-PhotoTaggr/Pods-PhotoTaggr-resources.sh"
Show environment variables in build log - ticked on
Run script only when installing- ticked on
````

Using CocoaPods 0.38.2

**Comment by segiddins** [comment]
@dmathewwws as this issue is closed, please open a new issue with the information requested in the contributing guidelines.

**Comment by freesuraj** [comment]
still has the issue at 0.39

**Comment by BillyLavoie** [comment]
Can confirm, getting the issue with 0.39
