### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftAppKit.dylib

### ISSUE THREAD

**Issue by anilkumarbp** [CocoaPods/CocoaPods#4340]
Hi,

I am trying to use the library through CoCoapods and when i build my project(Command Line Application) i get this error:

dyld: Library not loaded: @rpath/libswiftAppKit.dylib
Referenced from: /Users/-/Library/Developer/Xcode/DerivedData/src-eazezrghbafldbggbcexqohopyug/Build/Products/Debug/CryptoSwift.framework/Versions/A/CryptoSwift
Reason: image not found

Xocde Version : Version 7.0 (7A220)
Swift Version : Swift 2.0
OS Version : OS X 10.10.5

This is my Pod file :

use_frameworks!
platform :osx, '10.10'
target 'src' do
source 'https://github.com/CocoaPods/Specs'
pod 'CryptoSwift'
end

Would really appreciate your help on this.

**Comment by segiddins** [comment]
This should be fixed in the latest cocoapods beta?

**Comment by anilkumarbp** [comment]
$ gem which cocoapods
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0.rc.1/lib/cocoapods.rb

i am on the latest. Still does not work.

**Comment by neonichu** [comment]
Since it is a commandline application, see [this comment](https://github.com/CocoaPods/CocoaPods/issues/3709#issuecomment-122198485)
