### ISSUE TITLE
When using static libs, headers are copied flat to build dir, even with s.header_mappings_dir in place

### ISSUE THREAD

**Issue by TGOS** [CocoaPods/CocoaPods#4496]
The result is, when there is:

```
Pod/include/abc/BLAH.h
Pod/include/xyz/BLAH.h
```

and

```
s.header_mappings_dir = 'Pod/include'
```

then there will be only one `BLAH.h` in the build directory, top level. Expected would be

```
abc/BLAH.h
xyz/BLAH.h
```

instead. I mean, of what use is that `header_mappings_dir` setting anyway if it is pretty much ignored everywhere?

**Comment by neonichu** [comment]
This should've been fixed by #4057 in 0.39 — are you using that or an earlier version?

**Comment by TGOS** [comment]
# pod --version
    0.39.0

But maybe my `source_files` or `public_header_files` is wrong. Does `header_mappings_dir` require recursion? This setting is not really documented anywhere, other than to preserve the structure. My spec file is like this:

    s.source_files        = "Pod/include/abc/*.h", "Pod/src/*.{c,m,h}"
    s.public_header_files = "Pod/include/abc/*.h"
    s.header_mappings_dir = "Pod/include"

And the same for the xyz pod. In the `Pods/Headers` directory the structure is preserved but not in the products build dir where all headers are flat. Would I have to `change source_files` and `header_mappinds_dir` to use `"Pod/inlude/**/*.h"` instead?

**Comment by segiddins** [comment]
All your headers must be inside the headers mapping dir.

**Comment by TGOS** [comment]
So you say I need to set `header_mappings_dir` to `Pod/include/abc` when I want a directory `abc` in the build directory? That doesn't seem to match the documentation which says "A directory from where to preserve the folder structure for the headers files." (from where, to me that means everything below it, all directories, subdirectories, sub-subdirectories, etc.)

**Comment by segiddins** [comment]
No, that's true, but it looks like you also have headers in src that are not inside the headers mapping sir.

**Comment by TGOS** [comment]
This is correct, I have headers in `Pod/src` but these are not marked as public headers, they are only required to build the pod itself (not to use it later on) and these are not copied to the build dir at all (which is desired and IMHO also correct behavior). Other than that I have no headers in `Pod/include`, only in `Pod/include/abc` (and there is also no further sub-directory, all headers are in the folder `abc`).

**Comment by TGOS** [comment]
Okay, here's an update. I just saw that the generated build settings for the Pod are:

    PRIVATE_HEADERS_FOLDER_PATH = 
    PUBLIC_HEADERS_FOLDER_PATH = 

This alone cannot work. According to documentation

*PUBLIC_HEADERS_FOLDER_PATH*
*This is the location to copy the public headers during building, relative to the built products folder.*

If that is empty (and it is not empty because it was not set, Cocoapods explicitly set to an empty string in the target), Xcode will not create any directory for the headers, when copying the headers itself. As I have only one sub-directory, putting `abc` into that field will get me the desired and expected behavior.

But relying on Xcode to copy the headers together with their nested folder structure will not work anyway, Xcode will copy all headers marked as public flat to that directory, always. I was expecting Cocoapods to copy the headers  itself with a shell script (e.g. rsync'ing them to the build dir) as Xcode cannot do that to my best knowledge (not with a header copy phase) but that's what the documentation of the header_mappings_dir implied.

The directory structure is preserved nicely in `Pods/Headers` that's why the build works, but if you want to have the public headers later on in the build directory, they will always be flattened by the current method. In that case it would probably be better not to add these headers to a copy phase at all when static libraries are used. For static library it's not required to have the headers in the build dir at all (the headers are in the search path anyway, to using them in a build is not a problem even if they aren't copied).

**Comment by segiddins** [comment]
Ok, so from that last comment I'm having trouble understanding if there's an actual issue?

**Comment by TGOS** [comment]
The issue is that other targets (that are not linked with the pods) will search the build dir for headers, like this

    #import "abc/BLAH.H"

or

    #import "xyz/BLAH.h"

but they won't find them there. Of course I can change both lines to

    #import "BLAH.h"

that would be no problem and totally okay with me, except for one thing: `xyz/BLAH.h` is not the same header as `abc/BLAH.h` and one is overriding the other one if both are copied flat to the build dir. That the whole folder structure is not retained in the build dir and headers are flattened somewhat is something I can live with (my directory structure is always just on level deep anyway - doesn't make any sense to go deeper than that IMHO). So why don't you at least set the build settings like this:

    PRIVATE_HEADERS_FOLDER_PATH = $(NAME_OF_THE_POD)
    PUBLIC_HEADERS_FOLDER_PATH  = $(NAME_OF_THE_POD)

then I can do

    #import "PODNAME1/BLAH.h"

and 

    #import "PODNAME2/BLAH.h"

which is also totally fine, after all pod names are pretty stable. Within `PODNAMEx/` the headers would still be flat, but as I said above, this causes no issue and is probably tolerable. Maybe you don't just want set them to `$(NAME_OF_THE_POD)` but to `$(NAME_OF_THE_POD)-headers` or `include/$(NAME_OF_THE_POD)` (having headers in include is pretty common for most developers). These are only implementation details that have no direct influence on functionality, it may just look nicer when you look at the build dir (personal preference I guess).

**Comment by TGOS** [comment]
One annotation: Right now I'm referring to static libraries! If `use_frameworks!` is set, I'm not sure if that change is required. I don't even know if Xcode takes the `*_HEADERS_FOLDER_PATH` settings even into account in that case. If a framework is built, it's only important that the headers are copied into the framework... yet if there was another copy in directories as explained above, that wouldn't hurt anyone either as long as the frameworks will not contain these extra sub-direcotries in their internal header dir (that would of course be undesired).

**Comment by segiddins** [comment]
Try using bracket imports. If that doesn't work, we'll need a project we can run that clearly demonstrates the actual issue you're running into. Thanks!

**Comment by TGOS** [comment]
The problem is not that the header is not found, the problem is that flat headers in the build output dir overwrite each other, which they shouldn't do (they should be flat and thus also not overwrite each other). Maybe I can maybe work around by overriding `PUBLIC_HEADERS_FOLDER_PATH` in the Podspec or by using a hook in the Podpsec file. I have to test though if that is also compatible with `use_frameworks!` 

But just out of curiosity, is there any reason why you intentionally set `PUBLIC_HEADERS_FOLDER_PATH` to a blank string? By default it is `$(CONTENTS_FOLDER_PATH)/Headers` in Xcode and this will make sure headers are not copied flat.

**Comment by segiddins** [comment]
Yes, because it breaks archiving for static libs.

**Comment by TGOS** [comment]
When you say "for static libs", do you mean a static lib being built as the build target of the project and CP just adds some code to it? E.g. I have a static library target and I want to add AFNetworking to it using CP; is that the case you were referring to?

I'm just asking because I'm now trying to reproduce that issue as I can hardly believe that a path that only defines where headers are copied to can break archiving (Xcode won't even care for headers when archiving) and I've been using similar setups like that one for years (before I stated to use CP) and there was never a problem with copying headers or archiving to fail that would have forced me to blank these paths. So I'd really like to build a test setup to see myself what goes wrong and in case I can reproduce it, I'd like to analyze what the real cause of the problem is. Blanking these paths sounds to me like a dirty workaround but not like a real fix to an actual problem.

**Comment by TGOS** [comment]
Honestly, I see no reason why header need to be copied to the build directory at all. I just removed that by several projects by hand and instead added a the correct search paths and it works like a charm (and yes, even archiving, I tested with several projects). Writing umbrella headers the way you are currently doing makes Xcode search for includes all over the current target built (as it searches in User Search Path) and this will conflict whenever a header in the current project has the same name as a header from a Pod. So trying to be constructive, I think that CocoaPods should works as described in this document:

https://github.com/TGOS/PleaseFixCocoaPods/blob/master/README.md

It will hardly break anything existing Pod, it avoids all the problems I ever had with CP, it follows all recommendations of Apple, actually does everything the way Apple does it as well, all imports as safe and sane, umbrella headers are safe and sane and all developers (those writing pods and those using them) can follow a very simple, consistent pattern that will make sure it always works for them and anyone else.

Compared to that, your current implementation is a bit like "let's add every possible include directory to every possible search path and hope there is no conflicts, to every obscure and unused import scheme will work and hopefully not break". A bit like killing a bunch of ants by an atom bomb. Public headers are references in private directories and private directories are also added to public search paths for no particular benefit.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by pkieltyka** [comment]
Ive certainly had issues with this using pod 1.0.1, along with use_frameworks! .. quite brutal

**Comment by happycoloredbanana** [comment]
As requested by @neonichu here is a project for reproducing the problem:

- a C library distributed as a pod: https://github.com/happycoloredbanana/cpplibpod
- an iOS app using the above pod: https://github.com/happycoloredbanana/cpplibpoduser

Tested with cocapods 1.2.1

How to reproduce:
1.  Clone the two above repos into two sibling directories
1. In the ```cpplibpoduser``` directory run ```pod install```
1. ```open cpplibpoduser.xcworkspace``` and Run

What's wrong with it:
- a "Multiple build commands" warning is generated - this is caused by the fact that the library has two private header files with the same name but in different directories
- in the build directory (```~/Library/Developer/Xcode/DerivedData/cpplibpoduser-*/Build/Products/Debug-iphonesimulator/cpplibpod```) only one of the two ```defs.h``` is present, and since this directory is in the includes path (passed with a ```-I``` to the compiler) you cannot really guarantee what will be included. For instance, if the pod developer would use by mistake ```#include <>``` instead of ```#include ""``` this would create a not easily detectable bug.

The problem with warnings is also important: in one of my projects this generates hundreds of warnings (don't ask...) and results in  problems with Xcode.

**Comment by orta** [comment]
Looks like this should be re-opened then 👍

**Comment by happycoloredbanana** [comment]
The problem still exists in 1.3.0.beta.3.

**Comment by dnkoutso** [comment]
The issue hasn't had any PRs to designate it was fixed or updated.

**Comment by muxi** [comment]
We are still experiencing this issue in multiple pods ([gRPC-Core](https://cocoapods.org/pods/gRPC-Core), [BoringSSL](https://cocoapods.org/pods/BoringSSL)) in v1.3.1. Is there any plan on fixing this issue?

Similar to @TGOS, we found that removing the headers from Build Phases's private headers resolves this problem well. There seems to be not much reason the private headers need to be copied to build directory.

**Comment by paulb777** [comment]
CocoaPods is creating the requested structure. The issue is that Xcode also publishes public and private headers to a flat structure.
