### ISSUE TITLE
Pod install Xcode 7.1 ruby error

### ISSUE THREAD

**Issue by wolffan** [CocoaPods/CocoaPods#4546]
This is related to https://github.com/CocoaPods/CocoaPods/issues/4209 I'm opening again since the issue seems to be there.

Cocoapods version 0.37.2
XcodeProj version 0.28.2

Info:
Generating Pods project
2015-11-16 10:12:45.640 ruby[7637:73456] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-9079/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7f992ed88ec0>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x00000001058faf96 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x00000001058fa723 _DVTAssertionHandler (in DVTFoundation)
  2  0x00000001058fa98f _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x00000001058fa8f1 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x0000000106d4b6fd IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x0000000109526081 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x0000000109527c06 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff86999f44 ffi_call_unix64 (in libffi.dylib)
[1]    7637 abort      pod install

**Comment by zxcq99** [comment]
If you have still Xcode 6.4 installed changing xcode's path (`xcod-select -s`) to 6.4 ones helps (it did for me at least). It doesn't really solve the issue but you can use it as workaround if you are in hurry.

**Comment by wolffan** [comment]
@zxcq99 I uninstalled Xcode 6.4 and the current installation was done with xcode-install 7.1 from @neonichu .

**Comment by neonichu** [comment]
Please ensure the version of Xcodeproj in which this was fixed is actually being used.

**Comment by wolffan** [comment]
Changed the Xcodeproj version to 0.27.2 and still get the error

**Comment by neonichu** [comment]
Can only redirect you to [this comment](https://github.com/CocoaPods/CocoaPods/issues/4151#issuecomment-139083352) on how you could manually disable loading of the Xcode private frameworks as I cannot reproduce this.

**Comment by michaelochs** [comment]
@neonichu I do have the same issue now with Xcode 7.2

**Comment by michaelochs** [comment]
Never mind. The issue occurred only on cocoa pods 0.36 as I was in a project with an outdated Gemfile! No problems on cocoa pods 0.39!

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
