### ISSUE TITLE
Resource bundle has weird path?

### ISSUE THREAD

**Issue by a2** [CocoaPods/CocoaPods#4872]
There's something with quotes that it doesn't like? I'm not sure. This is on 1.0.0.beta.3.

<img width="891" alt="screen shot 2016-02-07 at 6 52 47 pm" src="https://cloud.githubusercontent.com/assets/241156/12882023/c3784412-ce4e-11e5-8730-05eee818d043.png">
![screen shot 2016-02-07 at 6 53 03 pm](https://cloud.githubusercontent.com/assets/241156/12882025/c398cbb0-ce4e-11e5-8d96-a5b8c46e5723.png)

**Comment by segiddins** [comment]
@efirestone could this be caused by your recent changes?

**Comment by efirestone** [comment]
Quite possible. I don't believe I'm generating any resource paths myself, but it's possible this is a combination of my changes and some less-tested code path somewhere. The issue definitely appears to be the generated path (note the `/Users/a2/Developer/Hydr8/Pods` at the beginning, followed by another full path). Perhaps this is an issue with the resource path being relative to the group, but also being defined as an absolute path.

@a2, some questions:

- Is it possible to provide your podspec, or at least the `.resources =` or `.resource_bundles =` part?
- Is this consistently reproducible?

In general, repro steps would help me look into it more. Thanks!

**Comment by a2** [comment]
@efirestone Yeah, it was reproducible, so I went back to 0.39.0.

The resource_bundles part of the podspec was:
```ruby
s.resource_bundles = { "Hydr8KitResources" => "Hydr8Kit/Resources/**/*" }
```

The path structure was:
Hydr8 > Hydr8Kit > Resources > Base.lproj > UnitTemplates.stringsdict

**Comment by efirestone** [comment]
I'm having trouble reproducing this locally.

Another thought: @segiddins could this be related to target de-duping? The issue is around the bundle itself and not the resources in it, so it seems like it might be at the target level.

@a2 Do you have multiple subspecs in the podspec that might be consuming this resources bundle (possibly indirectly)? Is it possible to get either a small sample project (ideal), or at least more of the podspec? Sorry for the trouble, and thanks for the help.

**Comment by a2** [comment]
@efirestone There aren't any subspecs. I'll try to get a small repro project together later today.

**Comment by basememara** [comment]
I'm getting the same error too. I have it reproducible in a project and seems to be related to when a pod is in multiple targets (like iOS and watch). This is the exact path error it's trying to look for: `"error: /Users/Me/Developer/Tests/MyCocoaPodsTest/Pods/"/Users/Me/Library/Developer/Xcode/DerivedData/MyCocoaPodsTest-drpnnwuhzipcoydmmeoisdayizyj/Build/Products/Debug-watchsimulator/Pods-MyCocoaPodsTestWatch Extension"/SomePod.bundle: No such file or directory"`

Here is the download to the test project: 
[MyCocoaPodsTest.zip](https://github.com/CocoaPods/CocoaPods/files/125863/MyCocoaPodsTest.zip)

**Comment by efirestone** [comment]
Awesome. Super helpful @basememara. @segiddins, looks like it's related to target de-deuplication. If you remove the second target that relies on the resources bundle (and corresponding framework), then everything seems to work fine.

The Podfile looks like this:
```
use_frameworks!

target "MyCocoaPodsTest" do
    pod 'ZamzamKit'
    
    target "MyCocoaPodsTestTests" do
        inherit! :search_paths
    end
    
end

target "MyCocoaPodsTestWatch Extension" do
    pod 'ZamzamKit'
end
```

If you remove the Watch extension target then everything works fine.

**Comment by orta** [comment]
@mrackwitz ^

**Comment by mrackwitz** [comment]
That might be already fixed by #4146, which addresses multiple issues in that direction.

**Comment by lucasderraugh** [comment]
I think the issue comes down to adding quotes around the PODS_FRAMEWORK_BUILD_PATH config variable. In 1.0.0 beta 3, it generates the following:
`PODS_FRAMEWORK_BUILD_PATH = "$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-DiningStack"`
 but in 0.39.0 it generates:
`PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-DiningStack`
Manually removing these quotes from the config file fixed my compile issues.

**Comment by basememara** [comment]
Good idea @lucasderraugh, but it didn't make a difference for my case. I think it may be because I have spaces in my project name unfortunately.

Also I noticed that v1b3 is creating an empty folder during `pod install`:
<img width="478" alt="capturfiles_275" src="https://cloud.githubusercontent.com/assets/892152/13035119/db01d992-d315-11e5-8149-60f5c1823380.png">

**Comment by inamiy** [comment]
@basememara
I also had the same double-quote directory issue in 1.0.0 beta 3. 

```
target :MyApp do
    pod 'CocoaLumberjack/Swift', '2.2.0', :configurations => ['Debug']
end
```

CocoaPods generates `Pods-MyApp-CocoaLumberjack` target, and when I build it manually, `path/to/MyApp/Pods/\"/Users/inamiy/Library/Developer/Xcode/DerivedData/MyApp-frhguffcyroqpwajetrrbcaezogy` is created, so Xcode couldn't find CocoaLumberjack headers.

**Comment by radazzouz** [comment]
I can consistently reproduce this issue using CocoaPods 1.0.0 beta 4 with an Objective-C project.

### Here's the content of my podfile

```
platform :ios, '7.0'

pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'master'

target 'ACME' do

end
```

### Here's the workaround

I worked around it by adding "1PasswordExtension" to `install_resource` path from the CocoaPods-generated `Pods-ACME-resources.sh` file.

```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource "${BUILT_PRODUCTS_DIR}/1PasswordExtension/OnePasswordExtensionResources.bundle"
fi
```

#### Here's the sample project that I used to test:

[ACME CocoaPods](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20CocoaPods.zip)

Hope that this helps.

Cheers!

**Comment by efirestone** [comment]
@radazzouz For yours I'm seeing slightly different behavior with the sample app (thanks btw!) than originally described in this issue. For yours, I'm seeing this message:

**Comment by efirestone** [comment]
Also, @radazzouz can you confirm that this is the same behavior you're seeing? If so, this probably needs a separate issue.

**Comment by radazzouz** [comment]
Hi @efirestone.

> can you confirm that this is the same behaviour you're seeing?

Yes. I confirm that we both are seeing the same issue. Basically, `1PasswordExtension` is missing from the path. So yes, the generated path and the expected path do not match.

> Did something change with where resource bundles are built, or where the copy-resources script looks for those bundles?

No, I did not change `resource_bundles` in our Podspec recently no did I change modify the copy-resources script prior to running `pod install`.

This issue's title and the screenshot for its description sounded like the same issue. Please feel free to open a separate issue if you think it's unrelated to this one.

All the Best,

**Comment by efirestone** [comment]
Thanks! And sorry, for the "did something change with..." question, that was for the CocoaPods developers.

I suspect this is a different issue than was originally described. Notice that in that case the path is malformed (`/Users/username/..` appears twice), likely related to quoting. This looks like a problem with building the path in the first place, and that CP may be leaving out a component.

I believe @mrackwitz was investigating the original issue. I'll leave it up to him on making the final call on whether this deserves a separate issue.

**Comment by radazzouz** [comment]
Thanks for the prompt reply @efirestone!

If there's anything I can do to help, please do not hesitate to ask :smile: 

Cheers!

**Comment by mrackwitz** [comment]
Thanks @efirestone for taking the lead on these investigations.

>Did something change with where resource bundles are built, or where the copy-resources script looks for those bundles?

Yes. All targets, including resources bundles, are built into another level of scoping inside the build dir to prevent name clashes and problems with search paths across dependencies, when there would be multiple variants. I'll have to take care that resources bundles are picked up from the right path..

**Comment by mrackwitz** [comment]
So what @radazzouz brought up here has actually a different root cause, but resources bundles remain broken, so we can keep tracking it together in this issue.

**Comment by Chandlerdea** [comment]
I am seeing this issue on 1.0.0.beta.6. Here is the error I am getting:

`error: /Users/chandlerdeangelis/Library/Developer/Xcode/DerivedData/Spinlister-dzfvgejluirikjcjutpycniwfzoj/Build/Products/Debug-iphonesimulator/1PasswordExtension/OnePasswordExtensionResources.bundle: No such file or directory`

The path to the bundle is:
 `/Users/chandlerdeangelis/Library/Developer/Xcode/DerivedData/Spinlister-dzfvgejluirikjcjutpycniwfzoj/Build/Products/Debug-iphonesimulator/1PasswordExtension/1PasswordExtension/OnePasswordExtensionResources.bundle`

So it seems like I am having the opposite problem that the original person had. The resource path is missing an additional 1PasswordExtension directory. Anyone else running into this?

**Comment by efirestone** [comment]
Have you tried with the 1.0.0 release? I don't remember which issues existed with which betas, but it's possible this was fixed already. If not, a sample project helps immensely.

**Comment by JianboYan** [comment]
I'm using pod 1.2.0 still have a similar issue here.
`error: Resource ".../Build/Products/Debug-iphonesimulator/MWPhotoBrowser/MWPhotoBrowser.bundle" not found. Run 'pod install' to update the copy resources script.`
