### ISSUE TITLE
Error pushing spec to repo

### ISSUE THREAD

**Issue by lucacorti** [CocoaPods/CocoaPods#4949]
- 🌈I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Run `pod repo push myrepo`
## What did you expected to happen?

The spec to be pushed to my private repo.
## What happened instead?

```
- ERROR | [iOS] unknown: Encountered an unknown error (uninitialized constant Fourflusher::Executable::Informative
/Library/Ruby/Gems/2.0.0/gems/fourflusher-0.3.0/lib/fourflusher/executable.rb:101:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/fourflusher-0.3.0/lib/fourflusher/executable.rb:58:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/fourflusher-0.3.0/lib/fourflusher/simctl.rb:16:in `simctl!'
/Library/Ruby/Gems/2.0.0/gems/fourflusher-0.3.0/lib/fourflusher/simctl.rb:10:in `list'
/Library/Ruby/Gems/2.0.0/gems/fourflusher-0.3.0/lib/fourflusher/find.rb:72:in `usable_simulators'
/Library/Ruby/Gems/2.0.0/gems/fourflusher-0.3.0/lib/fourflusher/find.rb:64:in `simulator'
/Library/Ruby/Gems/2.0.0/gems/fourflusher-0.3.0/lib/fourflusher/xcodebuild.rb:6:in `destination'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/validator.rb:705:in `xcodebuild'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/validator.rb:479:in `block in build_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/validator.rb:478:in `build_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/validator.rb:274:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/validator.rb:263:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/validator.rb:81:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/command/repo/push.rb:119:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/command/repo/push.rb:113:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/command/repo/push.rb:113:in `validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/command/repo/push.rb:58:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
) during validation.
```
## Podfile

``` ruby
Pod::Spec.new do |s|
  s.name         = "MySpec"
  s.version      = "1.2.25"
...
  s.license      = "Propietary"
  s.author       = { "Luca Corti" => "l@c.it" }
  s.platform = :ios, "9.0"
  s.source       = { :git => "myrepourl", :tag => s.version.to_s }
  s.source_files = "MySpec/*.{h,swift}"
  s.public_header_files = "MySpec/MySpec.h"
  s.dependency "AlamofireObjectMapper"
end
```

**Comment by neonichu** [comment]
Could you try running `xcrun simctl list` on the commandline?

**Comment by segiddins** [comment]
I think we can close this as a bug in fourflusher?

**Comment by neonichu** [comment]
@segiddins yes, but I'd like to keep it open so that I remember to update the dependency in CP once it has been fixed.

**Comment by lucacorti** [comment]
Apparently Xcode was missing from the machine I was trying to run cocoapods. The error message is somewhat unhelpful though.

**Comment by cahlbin** [comment]
FYI @neonichu, I can reproduce this when using a custom DEVELOPER_DIR path, e.g:

```
> export PATH=/Applications/Xcode72.app
> xcrun simctl list

2016-05-11 16:29:35.706 simctl[31455:889521] CoreSimulator is attempting to unload a stale CoreSimulatorService job.  Detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Applications/Xcode72.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework) and version (201.3) does not match existing job path (/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService) and version (209.19).
2016-05-11 16:29:36.716 simctl[31455:889521] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
```

So it's not necessarlily that Xcode / xcrun is not available, but `simctl` / `fourflusher` doesn't seem to play well with Xcode being in non-default location (i.e. `"Detected Xcode.app relocation or CoreSimulatorService version change"`)

**Comment by mrackwitz** [comment]
@neonichu: I think the original issue was fixed in flourflusher 0.3.1, but was is with the comment above from @cahlbin?

**Comment by ashfurrow** [comment]
I was having this issue on fourflusher 0.3.2, moving Xcode back to /Applications fixed it for me 👍 I had to `xcode-select` afterward. Is this an issue worth bringing up with fourflusher? I can open an issue.

**Comment by neonichu** [comment]
@ashfurrow You're still seeing the original issue? Or rather the one @cahlbin was mentioning?

Generally, I don't see a way to do any better than `xcrun simctl` itself — `fourflusher` is basically just a parser around its output.

**Comment by ashfurrow** [comment]
@neonichu I was experiencing the original problem, but the fix from @cahlbin to move Xcode back to its default location fixed the problem.

**Comment by neonichu** [comment]
Ugh, the original issue should have been solved by fourflusher 0.3.1 — could you please try uninstalling older versions of fourflusher if you have any? I remember us having an issue with loading the correct version because of our use of `autoload`.

**Comment by ashfurrow** [comment]
Oh I see, hmm. Four-flusher 0.3.2 was being used (based on the stack trace). It's hard to replicate, since I don't want to _actually_ push to trunk (and the computer this was happening on is at home). Any suggestions for reproducing, like is there a `--dry-run` flag or anything?

**Comment by neonichu** [comment]
You should be able to reproduce it using some bogus `DEVELOPER_DIR`, like `export DEVELOPER_DIR=yolo`
