### ISSUE TITLE
Dependencies are not being de-duplicated in test targets, using inherit! :search_path (aka Class is implemented in both)

### ISSUE THREAD

**Issue by fcy** [CocoaPods/CocoaPods#5253]
🌈
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

CocoaPods doesn't seem to be de-duplicating dependencies on test targets when test specific subspecs are involved. I've created a sample project that you can [download here](http://felipecypriano.com/files/deduplicatefail.zip).

The sample project has 1 app 3 pods and depends on 1 external pod. I've done it like this to simulate my real world project. This the overview of the dependency graph:

- App
 - sharedlib/Core
   - customlogging
- Test
 - sharedlib/Testing
   - testutils
     - customlogging
- customlogging
 - CocoaLumberjack

The problem is that CocoaLumberjack is duplicated in the Test target instead of just using the one available from the App target.

I'm using Cocoapods 1.0.0.rc.2

## What did you do?

1. Download the [sample project](http://felipecypriano.com/files/deduplicatefail.zip)
2. `cd sample/app`
3. Run `pod install`
4. Open `App.xcworkspace`
5. Select App scheme
6. CMD + U

## What did you expected to happen?

No message of classes being implemented in two targets.

## What happened instead?

CocoaLumberjack is duplicated in the test target, shown by these messages in the log:

>objc[42670]: Class PodsDummy_CocoaLumberjack is implemented in both /Users/felipe/Library/Developer/CoreSimulator/Devices/A7AC7786-BEE2-485C-99F8-9B6A6A50DC0B/data/Containers/Bundle/Application/CFF3A11E-AF33-4F63-AF87-3764D4CFD619/App.app/App and /Users/felipe/Library/Developer/Xcode/DerivedData/App-cgyiizastrqpkldshklktbsyaboa/Build/Products/Debug-iphonesimulator/App.app/PlugIns/Test.xctest/Test. One of the two will be used. Which one is undefined.
>objc[42670]: Class DDAbstractDatabaseLogger is implemented in both /Users/felipe/Library/Developer/CoreSimulator/Devices/A7AC7786-BEE2-485C-99F8-9B6A6A50DC0B/data/Containers/Bundle/Application/CFF3A11E-AF33-4F63-AF87-3764D4CFD619/App.app/App and /Users/felipe/Library/Developer/Xcode/DerivedData/App-cgyiizastrqpkldshklktbsyaboa/Build/Products/Debug-iphonesimulator/App.app/PlugIns/Test.xctest/Test. One of the two will be used. Which one is undefined.
>.....

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'App' do
  pod 'CocoaLumberjack'
  pod 'customlogging', path: '../customlogging'
  pod 'sharedlib/Core', path: '../sharedlib'

  target 'Test' do
    inherit! :search_paths

    pod 'testutils', path: '../testutils'
    pod 'sharedlib/Testing', path: '../sharedlib'
  end
end
```

**Comment by segiddins** [comment]
This is unfortunately unfixable with states libraries, but if you integrate your pods as frameworks, it'll work as expected.

**Comment by segiddins** [comment]
(i.e. add `use_frameworks!` to your podfile)

**Comment by fcy** [comment]
I'm in the process of converting my real world project to use frameworks but finding some problems, I thought this was related. On my real project when I change to framework the problem becomes "file not found CocoaLumberjack.h" (which sounds similar to this issue https://github.com/CocoaPods/CocoaPods/issues/5241).

I'll update the sample project when I manage to reproduce this problem in a concise sample.

**Comment by fcy** [comment]
@segiddins do you think file not found issues using frameworks could be related to using prefix header files?

**Comment by fcy** [comment]
I'm closing this issue since what I described is fixed by `use_frameworks!`.

**Comment by fcy** [comment]
Found the real problem and created a new issue for it: https://github.com/CocoaPods/CocoaPods/issues/5264

**Comment by arjunaud** [comment]
Hi, I am still getting the duplication issue on Cocoapods 1.5.3. The frameworks are being linked again in unit test target even after using use_framworks! and inherit!:search_paths. Could you please help me with this?
