### ISSUE TITLE
"Code Coverage Data Generation Failed" while running tests

### ISSUE THREAD

**Issue by bsarrazin** [CocoaPods/CocoaPods#5385]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I upgrade our project form `0.39` to `1.0`
## What did you expected to happen?

I expected to be able to run our tests properly.
## What happened instead?

I keep getting this error:
![image](https://cloud.githubusercontent.com/assets/1077441/15438454/3ff65380-1e9a-11e6-82c2-26ff86531171.png)
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/berzerker/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b505e9434877b77b63b1c141d599243ef2583cdf
```
### Installation Source

```
Executable Path: /Users/berzerker/.rbenv/versions/2.3.1/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
inhibit_all_warnings!
platform :ios, '9.0'

target 'MyTarget' do

  use_frameworks!

  pod 'ActionKit', '1.0'
  pod 'AFNetworking', '1.3.4'
  pod 'Analytics', '3.0.7'
  pod 'AppsFlyerFramework', '4.4.1'
  pod 'ARSPopover', '2.2.1'
  pod 'AsyncImageView', '1.5.1'
  pod 'BKPasscodeView', '0.2.2'
  pod 'Crashlytics', '3.7.0'
  pod 'Fabric', '1.6.7'
  pod 'FBSDKLoginKit', '4.12.0'
  pod 'GoogleAnalytics', '3.14.0'
  pod 'GoogleConversionTracking', '3.4.0'
  pod 'GPUImage', '0.1.7'
  pod 'JazzHands', '2.0.8'
  pod 'libPhoneNumber-iOS', '0.8.12'
  pod 'ODRefreshControl', '1.2'
  pod 'Optimizely-iOS-SDK', '1.4.2'
  pod 'pop', '1.0.9'
  pod 'RSKImageCropper', '1.5.1'
  pod 'Stripe', '6.2.0'
  pod 'TTTAttributedLabel', '1.13.4'
  pod 'ZBarSDK', '1.3.1'
  pod 'ZendeskSDK', '1.6.0.1'

  target 'MolokiniLogicTests' do
    inherit! :search_paths
    pod 'OCMock', '3.3'
    # These are required for now because of our current testing setup.
    pod 'AppsFlyerFramework', '4.4.1'
    pod 'BKPasscodeView', '0.2.2'
    pod 'Crashlytics', '3.7.0'
    pod 'GoogleAnalytics', '3.14.0'
    pod 'Optimizely-iOS-SDK', '1.4.2'
    pod 'Stripe', '6.2.0'
    pod 'TTTAttributedLabel', '1.13.4'
  end

  target 'MolokiniUITests' do
    inherit! :search_paths
  end

end

post_install do |installer|
    puts("Update debug pod settings to speed up build time")
    Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
        File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
    end
end
```
## Project that demonstrates the issue

I can't provide the repo to our project.
But reverting back to CocoaPods 0.39 fixes the issue.

**Comment by neonichu** [comment]
Are you experiencing this when running your unit or your UI tests?

**Comment by bensarz** [comment]
@neonichu unit tests, note that the tests aren't hosted, could this be impacting this?
![image](https://cloud.githubusercontent.com/assets/1077441/15438856/1b1d5994-1e9c-11e6-9825-9cc654dbd334.png)

**Comment by neonichu** [comment]
I have definitely seen using UIKit without a test host causing issues — it's curious that this depends on switching CocoaPods versions, though. I assume you were also using `use_frameworks!` before?

**Comment by bensarz** [comment]
Yes, were were always using `use_frameworks!`

**Comment by startupthekid** [comment]
This also happened to me but only with testing on a device, not a simulator. And I can confirm, 0.39 was fine but 1.0.0 made everything go crazy.

**Comment by neonichu** [comment]
Don't see a good way to debug this without a test project, unfortunately. Let us know if one of you figures out how to reproduce it, thanks!

**Comment by nunogoncalves** [comment]
Hi! 
I am having the same problem. I get the same message:
I can record a ui test case, but then I cannot run it. (gif bellow)
![octopodiumuitests](https://cloud.githubusercontent.com/assets/3007012/16007942/3117bc10-316d-11e6-816a-92a91cde3633.gif)

This happens on the repo:
https://github.com/nunogoncalves/iOS-OctoPodium

**Comment by dfleming** [comment]
For some reason, it appears that CocoaPods is not adding the "[CP] Embed Pods Frameworks" build phase to the UI Tests target when generating the project workspace.

I manually added this in and the UI Tests were runnable again. 

This build phase should run the following script: (Replace {YourProject} with your project name)
```
"${SRCROOT}/Pods/Target Support Files/Pods-{YourProject}UITests/Pods-{YourProject}UITests-frameworks.sh"
```

**Comment by DanToml** [comment]
@dfleming The UI Tests embedding bug has been fixed in master

**Comment by skyem** [comment]
I'm seeing this too when running KIF tests which are unit tests with code coverage. It only happens when running them on a device.

**Comment by Blackjacx** [comment]
For me happens the same as for @skyem :-(

**Comment by DanToml** [comment]
Closing due to lack of activity (also I'm pretty sure this is fixed now)

**Comment by marcelvoss** [comment]
It isn't fixed and still happening to us. We ran into the exact same issue during UI tests. @DanToml

**Comment by dnkoutso** [comment]
@marcelvoss this is a rather old issue with CocoaPods 1.0.0 version reported. Please file a new issue using the template and hopefully a sample app that makes it easier for us to debug it and fix it.

**Comment by amardeepranu** [comment]
Also getting this issue

**Comment by reshadf** [comment]
I am getting this issue as well when running UI tests

**Comment by TheMetalCode** [comment]
Up until yesterday afternoon I was seeing this issue with my UI test bundle as well.

The issue went away for me when I relocated the target definition in the Podfile.

Before, I was defining my UI tests target inside the main target like so:

```
target 'MyApp' do
  use_frameworks!
  inhibit_all_warnings!

  app_pods

  target 'MyAppTests' do
    inherit! :search_paths
    testing_pods
  end
  
  target 'MyAppUITests' do
    inherit! :search_paths
    testing_pods
  end
end
```

I changed it to look like this:

```
target 'MyAppUITests' do
    use_frameworks!
    inhibit_all_warnings!
    testing_pods
  end

target 'MyApp' do
  use_frameworks!
  inhibit_all_warnings!

  app_pods

  target 'MyAppTests' do
    inherit! :search_paths
    testing_pods
  end
end
```

Your mileage may vary.
