### ISSUE TITLE
Bundle Identifier missing in info.plist in Xcode simulator logs

### ISSUE THREAD

**Issue by Abhishek9634** [CocoaPods/CocoaPods#5774]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I have created my own cocoapod of a framework project in objective-c.
and the test in sample project to cross check
simply `pod install`
and run the project but it is giving error every time 

![5u2jd](https://cloud.githubusercontent.com/assets/10388287/17852483/3829aa64-6885-11e6-8f8d-b1607ec8dfc3.png)

I checked in simulator logs also 

`Aug 22 13:31:01 devashishs-MacBook-Air CoreSimulatorBridge[1222]: 0x700000117000 __MobileInstallationInstallForLaunchServices_block_invoke222: Returned error Error Domain=MIInstallerErrorDomain Code=12 "Bundle at path /Users/devashish/Library/Developer/CoreSimulator/Devices/A3D7C8F0-D6E9-4A9E-BC21-6E2FF83352D8/data/Library/Caches/com.apple.mobile.installd.staging/temp.FeZyHO/extracted/PodCheck.app/Frameworks/Myframework.framework did not have a CFBundleIdentifier in its Info.plist" UserInfo={LegacyErrorString=MissingBundleIdentifier, FunctionName=-[MIBundle _validateWithError:], SourceFileLine=37, NSLocalizedDescription=Bundle at path /Users/devashish/Library/Developer/CoreSimulator/Devices/A3D7C8F0-D6E9-4A9E-BC21-6E2FF83352D8/data/Library/Caches/com.apple.mobile.installd.staging/temp.FeZyHO/extracted/PodCheck.app/Frameworks/Myframework.framework did not have a CFBundleIdentifier in its Info.plist}`

i checked again but everywhere bundle identifier is present. I googled and tried
1. Reset content and setting
2. Clear derived data and cache
3. Clean and build
4. Restart xcode
5. uninstall and install cocoapods

But none of them work, I'm stucked here please help

**Comment by neonichu** [comment]
Please share a project which reproduces the issue.

**Comment by Abhishek9634** [comment]
Ok Check this : 
[PodCheck.zip](https://github.com/CocoaPods/CocoaPods/files/429955/PodCheck.zip)

**Comment by Abhishek9634** [comment]
I removed `use_frameworks!` in pod project and as well as sample one(as this is used for swift project)
Now it is showing "installation failed invalid argument"

**Comment by Abhishek9634** [comment]
@neonichu : Any Luck???

**Comment by adriengabriel** [comment]
@Abhishek9634 Did you find a solution I got the same problem with Moya/Result pods
Thank you !

**Comment by Abhishek9634** [comment]
yes for me it is coming because in my pod file i used " ` " in place of " ' "
example :  pod 'Almofire', '2.3`    :  see in last  after 2.3

**Comment by adriengabriel** [comment]
@Abhishek9634 ok thanks, unfortunately it seems that I dont any problematic characters within my pod file so it must be something else

**Comment by Abhishek9634** [comment]
OK and the second things is in podspec : 

s.source_files  = "MyPod", "MyPod/**/*.{h,m}"

s.resources = 'MyPod/**/*.{lproj,storyboard,xcdatamodeld,xib,xcassets,json}'

here mypod name and root directory name is same

**Comment by dlo** [comment]
@Abhishek9634 could you reopen this issue? I'm seeing the same thing with another project.

**Comment by adriengabriel** [comment]
@dlo for information, I've fixed it by putting the missing field into the plist file of my pod... Of course it's not the best solution, a maybe a temporary one but at least you could work :)

**Comment by Abhishek9634** [comment]
@adriengabriel :: In my case bundle identifier is present in info.plist but still i faced that issue

**Comment by dlo** [comment]
@Abhishek9634 Didn't work. The CFBundleIdentifier key was in the Pod and installation still failed. I think it's a caching issue of some sort.

**Comment by Abhishek9634** [comment]
can tou try to create pod of a fresh project

**Comment by AJShippify** [comment]
My project everytime it's run pops an error alerting Bundle at path *.framework did not have a CFBundleIdentifier in its Info.plist.

Is this related somehow to this thread?

**Comment by Abhishek9634** [comment]
For different types of issue same error pops for my above mentioned it is coming

**Comment by AJShippify** [comment]
Is there a way to fix this?

**Comment by Abhishek9634** [comment]
Then you can try the solutions 
whatever i tried , mentioned above may this helps

**Comment by lindow2009** [comment]
i have some issues about cocoapods that alerting Bundle at path *.framework did not have a CFBundleIdentifier in its Info.plist
so have any ideas?

**Comment by KirtyBB** [comment]
Have you tried 
pod deintegrate
then 
pod install
