### ISSUE TITLE
'pod spec lint' fails with message 'App.xcworkspace' does not exist. 🌈

### ISSUE THREAD

**Issue by psturm-swift** [CocoaPods/CocoaPods#5805]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run 'pod spec lint --verbose' on 'https://github.com/psturm-swift/SwiftySignals/blob/Swift_3.0/SwiftySignals.podspec'

## What did you expect to happen?
I expect that the validation passes.

## What happened instead?
Validation ends with an error saying that App.xcworkspace does not exist. However, if I run pod spec lint with option --no-clean the workspace is there but it is not found by pod spec lint.

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8S201h)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/psturm/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 34ac2d09edb2bf66b9cb6badcccdc32c99fd1192
```

### Installation Source

```
Executable Path: /Users/psturm/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/psturm-swift/SwiftySignals/tree/Swift_3.0

**Comment by segiddins** [comment]
This is probably due to the Xcode 8 chdir issue

**Comment by cnoon** [comment]
We're seeing the same issue with our Willow [podspec](https://github.com/Nike-Inc/Willow/blob/master/Willow.podspec) on `1.1.0-beta.2`. 

Is this to be expected right now @segiddins due to the chdir issue? Should those of us looking to cut releases due to the GM drop today just submit podspecs to the specs repo directly? Should we just wait for now? Just looking for some direction since we're planning on cutting 10+ releases today between all the Alamofire libs and Nike OSS libraries.

Thanks as always! 🍻

**Comment by orta** [comment]
We've just merged the PR fixing that 👍, and are chatting ATM about trying to get a 1.1.0 RC asap

**Comment by DanToml** [comment]
@cnoon I'm just running the test suites against the GM build of Xcode right now, if everything passes, I hope to have an RC out in the next couple of hours.

**Comment by jshier** [comment]
@cnoon @orta Unfortunately we'll still have issues pushing to trunk due to #5650. Unless there's a way to turn off the linting or otherwise force a push?

**Comment by DanToml** [comment]
@jshier You should be able to handle this by setting a custom `pod_target_xcconfig` that sets the `SWIFT_VERSION`?

**Comment by jshier** [comment]
@DanToml See #5796 for my attempt to work around the issue.
