### ISSUE TITLE
CocoaPods 1.1.0.beta.2, target frameworks conflicting names

### ISSUE THREAD

**Issue by mltk96** [CocoaPods/CocoaPods#5836]
# Report

## What did you do?
installed CocoaPods version 1.1.0.beta.2
and run pods install on my project

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
got the following error: "The 'Pods-XXX' target has frameworks with conflicting names:...."

**Comment by DanToml** [comment]
This is caused by an issues where opening a project with Xcode 8 breaks chdir. A fix has been merged in Xcodeproj and will be released in RC 1. Please check #5825 for updates.

**Comment by mltk96** [comment]
just installed RC2, and still have that issue.
any suggestions?

**Comment by DanToml** [comment]
@mltk96 could you please share a Podfile or project that reproduces this please?

**Comment by mltk96** [comment]
yes.
my pods looks something like:

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "9.0"

use_frameworks!

def sharedPods
    pod 'Fabric'
    pod 'Alamofire', '3.5'
end

def mainPods
    pod 'Mixpanel'
    sharedPods
end

def extensionPods
    pod 'Mixpanel/AppExtension'
    sharedPods
end

target ‘MainApp’ do
    mainPods
end

target ‘ShareExtensionApp’ do
    extensionPods
end


and the error is:
The 'Pods-MainApp' target has frameworks with conflicting names: mixpanel.

**Comment by Thomvis** [comment]
I'm also seeing this with 1.1.0 rc1. In my case it complains about Bolts. I'm defining `Bolts/Tasks` as a dependency of both an extension target and an app target. If I use the main-spec instead of the subspec, the `pod install` succeeds.

**Comment by mltk96** [comment]
@DanToml any updates?

**Comment by mltk96** [comment]
@DanToml any updates on the issue?

**Comment by zierka** [comment]
This seems to be bug #5643
