### ISSUE TITLE
pod trunk push: "xcodebuild: error: 'App.xcworkspace' does not exist."

### ISSUE THREAD

**Issue by malcommac** [CocoaPods/CocoaPods#5843]
# Report
I've tried to make a `pod trunk push` of my cocoapod lib using XCode 8 (used `sudo xcode-select -s /Applications/Xcode.app` where Xcode.app is v. 8) and process if failed with this error:

## What did you do?

`pod trunk push`

## What did you expect to happen?

New version should be pushed.

## What happened instead?

Failed to push with error:

```
[!] Found podspec `xxx.podspec`
Updating spec repo `master`

CocoaPods 1.1.0.rc.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.1

Validating podspec
 -> xxx (1.0.6)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/xxx/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2e52a5c8dc155a94947515ea5728ca3b990e9b82
```

### Installation Source

```
Executable Path: /Users/xxx/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by jonasman** [comment]
that is fixed on CocoaPods `1.1.0.rc.1`

**Comment by benasher44** [comment]
Yep!

**Comment by malcommac** [comment]
Cool, I've tried to update using
```
sudo gem install cocoapods --pre
```
but I still get 

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/danielemargutti/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2e52a5c8dc155a94947515ea5728ca3b990e9b82
```

### Installation Source

```
Executable Path: /Users/danielemargutti/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

What's wrong?

**Comment by malcommac** [comment]
Okay seems I've installed three different versions of cocoapods.
Removed using sudo ```gem uninstall cocoapods``` and installed again via``` sudo gem install cocoapods --pre```

**Comment by CNKCQ** [comment]
the same error

**Comment by malcommac** [comment]
uninstall all cocoapods version reinstall and reset your pods. It should work fine.

**Comment by fulldecent** [comment]
I updated to 1.1.0.rc.2 not it give me a bunch of errors because it is not recognizing this is a Swift 3 project.

**Comment by hectormatos2011** [comment]
I'm getting the same error when updating to the latest rc

**Comment by hectormatos2011** [comment]
I take that back. To be clear, I'm getting this issue on non rc version of 1.0.1. When updating to 1.1.0.rc.2, I'm also getting errors from xcodebuild that look as though it doesn't know what Swift 3 is even though Xcode 8 is the only environment I have on my machine.

**Comment by hectormatos2011** [comment]
@neonichu and @segiddins, don't know if you guys are working on this or not, but [PrediKit](https://github.com/KrakenDev/PrediKit) on the master branch has this issue when doing a `pod trunk push`. Updating to 1.1.0.rc.2 fixes the issue but won't compile the project after my conversion to Swift 3.

**Comment by hectormatos2011** [comment]
Figured it out. @fulldecent I know you're having this problem too. In case you haven't figured it out yet, go to where your podspec is, and execute this command in terminal:

```bash
echo 3.0 > .swift-version
```

Try a `pod trunk push` again and see it that works for you

**Comment by hectormatos2011** [comment]
@neonichu && @segiddins, you can ignore me now.

**Comment by neonichu** [comment]
Ya tu sabes

**Comment by guidev** [comment]
same here

**Comment by fulldecent** [comment]
@hectormatos2011 Thank you, this worked. I added that step to a full recipe for people making Swift 3 modules at:

 > https://github.com/fulldecent/swift3-module-template
