### ISSUE TITLE
Nanaimo parse error

### ISSUE THREAD

**Issue by dorotakrimmel** [CocoaPods/CocoaPods#6108]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
### Command

```
/usr/local/bin/pod install
```
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3e9622eca9051c5d30231c8c71074d5b4ce29ab1
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'TrakCar_LANG_Arabic' do
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'GoogleUtilities'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'mopub-ios-sdk'
#pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
#pod 'AdMobMediationAdapterFlurry'
end

target 'TrakCar_LANG_German' do
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'GoogleUtilities'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'mopub-ios-sdk'
#pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
#pod 'AdMobMediationAdapterFlurry'
end

target 'TrakCar_LANG_BrazPortuguese' do
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'GoogleUtilities'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'mopub-ios-sdk'
#pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
#pod 'AdMobMediationAdapterFlurry'
end

target 'TrakCar' do
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'GoogleUtilities'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'mopub-ios-sdk'
#pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
#pod 'AdMobMediationAdapterFlurry'
end

target 'TrakCar_LANG_Polish' do
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'GoogleUtilities'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'mopub-ios-sdk'
#pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
#pod 'AdMobMediationAdapterFlurry'
end

target 'TrakCar_LANG_Russian' do
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'GoogleUtilities'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'mopub-ios-sdk'
#pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
#pod 'AdMobMediationAdapterFlurry'
end

target 'TrakCar_LANG_Spanish' do
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'GoogleUtilities'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'mopub-ios-sdk'
#pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
#pod 'AdMobMediationAdapterFlurry'
end

target 'TrakCar_LANG_Swahili' do
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'GoogleUtilities'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'mopub-ios-sdk'
#pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'
#pod 'AdMobMediationAdapterFlurry'
end
```
### Error

```
Nanaimo::Reader::ParseError - Array [#<Nanaimo::String:0x007fe94715d0a0 @value="LANG_POLISH", @annotation="">, #<Nanaimo::QuotedString:0x007fe94715cd80 @value="APP_VERSION=@\\", @annotation="">] missing ',' in between objects
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:251:in `raise_parser_error'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:140:in `parse_array'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:100:in `parse_object'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/usr/local/lib/ruby/gems/2.3.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:73:in `parse!'
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:102:in `open'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by orta** [comment]
What are the ENV variables being set around languages in your xcode projects look like?

**Comment by dorotakrimmel** [comment]
Not sure where to check it.
Update - this happens after I run:
pod deintegrate
This command corrupts xcodeproj file (and removes xcworkspace), after I checked out the full repository from git I was able to run both pod install and pod update. But pod deintegrate corrupts everything and after this every pod command produces the above error.
This started happening today after I updated Xcode to version 8.1, before this pod deintegrate worked like a charm. Reinstalling cocoapods or upgrading to cocoapods 1.2 (beta) yeild the same problem, pod deintegrate corrupts the project.

**Comment by segiddins** [comment]
Please share your project file so we can see why parsing is failing. Thanks!

**Comment by skrew** [comment]
Just for info, i have the same problem.
Updating nanaimo to v0.1.2 don't help.

Usually i use a hint for that:
pod _0.39.0_ install

but now it's fail with:
```
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface/error_report.rb:13:in `report': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:61:in `report_error'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:374:in `handle_exception'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:315:in `rescue in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
@skrew 

> Please share your project file so we can see why parsing is failing. Thanks!

**Comment by dorotakrimmel** [comment]
@segiddins 
Project file - which one is that? I am new to this forum. Do you mean my Podfile?
Or the corrupt .xcodeproj after pod deintegrate makes it unreadable?
Or some other file?

**Comment by dorotakrimmel** [comment]
Here they are. This is BEFORE the corruption happens (no errors on that one)
WORKING ONE:
[project_before_corrupt.pbxproj.zip](https://github.com/CocoaPods/CocoaPods/files/561326/project_before_corrupt.pbxproj.zip)

This is the corrupted one, after I ran pod deintegrate. After this pod install (or pod update, or pod deintegrate) cause the Nanaimo::Reader::ParseError I am reporting here.
CORRUPTED ONE:
[project_after_deintegrate_corrupted.pbxproj.zip](https://github.com/CocoaPods/CocoaPods/files/561331/project_after_deintegrate_corrupted.pbxproj.zip)

**Comment by alexey-bondar** [comment]
I've got the same problem after updating my gems. Try to downgrade the version of xcodeproj gem.

sudo gem uninstall xcodeproj
sudo gem install -n /usr/local/bin xcodeproj -v 1.3.2

**Comment by germs5** [comment]
I had a similar error:

pod install
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 32400f6bbcd694ed9a0d1268d3a3934835bea6cd
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

workspace 'FlixwagonGlideSDK'

target 'GlideNetSDK' do
	project '../../glide-net-sdk/iOS/GlideNetSDK/GlideNetSDK.xcodeproj'
	pod 'Protobuf', '~> 3.1.0'
end

target 'GlideiPhoneDebugFW' do
	project '../../glide-ios/GlideProject/GlideiPhone.xcodeproj'
	pod 'PubNub'
	pod 'Protobuf', '~> 3.1.0'
	pod 'ios-ntp'
	pod 'CTAssetsPickerController',  '~> 3.3.0'
end
```

### Error

```
Nanaimo::Reader::ParseError - Array [#<Nanaimo::QuotedString:0x007fa064978810 @value="$(inherited)", @annotation="">, #<Nanaimo::QuotedString:0x007fa064983990 @value="SELECTED_SE_IS_EXTERNALY_DEFINED=$(SELECTED_SE_IS_EXTERNALY_DEFINED)", @annotation="">, #<Nanaimo::QuotedString:0x007fa064982ea0 @value="IS_FOR_DEBUG=$(IS_FOR_DEBUG)", @annotation="">, #<Nanaimo::QuotedString:0x007fa064982658 @value="IS_FOR_APP_STORE=$(IS_FOR_APP_STORE)", @annotation="">, #<Nanaimo::QuotedString:0x007fa064981eb0 @value="SELECTED_SE=$(SELECTED_SE)", @annotation="">, #<Nanaimo::QuotedString:0x007fa0649817d0 @value="NIGHTLY_FLAG=$(NIGHTLY_FLAG)", @annotation="">, #<Nanaimo::QuotedString:0x007fa064980c40 @value="GLIDE_BUNDLE_ID_STRING=@\\", @annotation="">] missing ',' in between objects
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:251:in `raise_parser_error'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:140:in `parse_array'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:100:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:73:in `parse!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Array+%5B%23%3CNanaimo%3A%3AQuotedString%3A0x007fa064978810+%40value%3D%22%24%28inherited%29%22%2C+%40annotation%3D%22%22%3E%2C+%23%3CNanaimo%3A%3AQuotedString%3A0x007fa064983990+%40value%3D%22SELECTED_SE_IS_EXTERNALY_DEFINED%3D%24%28SELECTED_SE_IS_EXTERNALY_DEFINED%29%22%2C+%40annotation%3D%22%22%3E%2C+%23%3CNanaimo%3A%3AQuotedString%3A0x007fa064982ea0+%40value%3D%22IS_FOR_DEBUG%3D%24%28IS_FOR_DEBUG%29%22%2C+%40annotation%3D%22%22%3E%2C+%23%3CNanaimo%3A%3AQuotedString%3A0x007fa064982658+%40value%3D%22IS_FOR_APP_STORE%3D%24%28IS_FOR_APP_STORE%29%22%2C+%40annotation%3D%22%22%3E%2C+%23%3CNanaimo%3A%3AQuotedString%3A0x007fa064981eb0+%40value%3D%22SELECTED_SE%3D%24%28SELECTED_SE%29%22%2C+%40annotation%3D%22%22%3E%2C+%23%3CNanaimo%3A%3AQuotedString%3A0x007fa0649817d0+%40value%3D%22NIGHTLY_FLAG%3D%24%28NIGHTLY_FLAG%29%22%2C+%40annotation%3D%22%22%3E%2C+%23%3CNanaimo%3A%3AQuotedString%3A0x007fa064980c40+%40value%3D%22GLIDE_BUNDLE_ID_STRING%3D%40%5C%5C%22%2C+%40annotation%3D%22%22%3E%5D+missing+%27%2C%27+in+between+objects&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
/Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.2/lib/gh_inspector/sidekick.rb:83:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.2/lib/gh_inspector/sidekick.rb:32:in `search'
	from /Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.2/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.2/lib/gh_inspector/inspector.rb:59:in `search_exception'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:65:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

**Comment by Rulikkk** [comment]
```
sudo gem uninstall xcodeproj
sudo gem install -n /usr/local/bin xcodeproj -v 1.3.3
```

This seems to work. Note: I changed version to `1.3.3`. Looks like we need to report to Nanonimo?

**Comment by segiddins** [comment]
So this appears to actually be a serialization error -- the backslash before the quote is being escaped when it shouldn't be?

**Comment by segiddins** [comment]
Yup, this is a bug in `Nanaimo::Unicode.unquotify_string`

**Comment by dorotakrimmel** [comment]
@segiddins do you have any advice on how to work around it until nanaimo fixes their bug?

**Comment by dorotakrimmel** [comment]
@Rulikkk I tried your solution, it did not solve the problem for me, I am still getting an error. Does anyone know of any workaround, while we wait for Nanaimo to fix their bug?

**Comment by segiddins** [comment]
I'm working on a patch for nanaimo this week

**Comment by segiddins** [comment]
This should be fixed in Nanaimo 0.2.1

**Comment by chiahsien** [comment]
I'm using Nanaimo 0.2.2, it seems that this issue still exists.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.0 (8A218a)
         Git : git version 2.10.2
Ruby lib dir : /usr/local/var/rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 33f6caeb445752bb476651a4e1bd6108adb6217f
               zendesk - https://github.com/zendesk/Specs.git @ 6104d15ad9bdd50a8ce57bab00dccebea7d6404b
```

### Error

```
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
    #  -------------------------------------------
    #  					"COCOAPODS=1",
    #  					"$(inherited)",
4953>  					"BITHOCKEY_VERSION=\"@\\"3.6.2\\"\"",
       					                         ^
    #  					"BITHOCKEY_C_VERSION=\"\\"3.6.2\\"\"",
    #  					"BITHOCKEY_BUILD=\"@\\"35\\"\"",
    #  -------------------------------------------

/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:173:in `parse_array'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:133:in `parse_object'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:131:in `parse_object'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:131:in `parse_object'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:131:in `parse_object'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:131:in `parse_object'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.2/lib/nanaimo/reader.rb:106:in `parse!'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:27:in `read_from_path'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:695:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `each'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `block in inspect_targets_to_integrate'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:689:in `inspect_targets_to_integrate'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/var/rbenv/versions/2.2.2/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.2.2/bin/pod:23:in `<main>'
```

**Comment by tarun29061990** [comment]
Any update on this? I am using nanaimo 0.2.6 and I am getting error while doing pod install. 

### Error

```
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
   #  -------------------------------------------
   #  			sourceTree = "<group>";
   #  		};
263>  		5D96C02C2E854BCA87D8C9B6 /* Resources */ = {
      		                                         ^
   #  			isa = PBXGroup;
   #  			children = (
   #  -------------------------------------------

/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:174:in `parse_array'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:134:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.12.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.12.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.12.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/command/deintegrate.rb:40:in `validate!'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by doozMen** [comment]
still present
