### ISSUE TITLE
Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.

### ISSUE THREAD

**Issue by invious** [CocoaPods/CocoaPods#6243]
Trying to do `pod install` have tried so many so-called fixes and have failed. I've been trying to do pod install for four hours now.

I've tried

1. `sudo xcode-select -r`

2.
```
rm -rf  ~/.cocoapods/repos/master
git clone https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master
```

and all manner of things.

**Comment by benasher44** [comment]
HI there! We'd be happy to help! Can you please post output of `pod env`? Thanks!

**Comment by wpapper** [comment]
I encountered this issue, and ended up installing Specs manually from `master`. However, now I'm running into the following error (possibly related) when I try to run `pod install`.

`pod env` leads to the same error appearing. I was following the instructions from [react-native-maps](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md).

```
➜  GitRepo git:(master) ✗ pod install --verbose
  Preparing
[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at /Users/user/.cocoapods/repos/master/CocoaPods-version.yml
---
min: 1.0.0
last: 1.2.0.beta.1
prefix_lengths:
- 1
- 1
- 1


/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/yaml_helper.rb:62:in `rescue in load_string'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/yaml_helper.rb:57:in `load_string'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/yaml_helper.rb:75:in `load_file'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/metadata.rb:27:in `from_file'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source.rb:412:in `refresh_metadata'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source.rb:27:in `initialize'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:287:in `new'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:287:in `block in source_from_path'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:292:in `yield'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:292:in `source_from_path'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:301:in `block in aggregate_with_repos'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:301:in `map'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:301:in `aggregate_with_repos'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:24:in `aggregate'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:61:in `all'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:346:in `source_with_url'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:18:in `find_or_create_source_with_url'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:814:in `block in sources'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `map'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `sources'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/user/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/user/.rvm/rubies/ruby-2.1.2/bin/pod:23:in `load'
/Users/user/.rvm/rubies/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/user/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wpapper** [comment]
I fixed the second error by uninstalling Psych

**Comment by Sonictherocketman** [comment]
Having the same issue. Pod worked before I updated it, once I did I get this error. I've uninstall/reinstalled and it still occurs. Setup appears to go fine, but `pod install` fails.

### Command

```
/usr/local/bin/pod install
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8B62)
         Git : git version 1.8.4
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 00fb4e47a1aae6d94a1a67c0b5aed299fd576b45
               master-1 - https://github.com/CocoaPods/Specs.git @ 448dbca451ff99e8d8724842e06fae821aee26fc
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Hewell' do
    pod 'Locksmith', '~> 3.0.0'
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireObjectMapper', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
```

### Error

```
RuntimeError - Unable to create a source with URL https://github.com/CocoaPods/Specs.git
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:42:in `find_or_create_source_with_url'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:814:in `block in sources'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `map'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `sources'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
@wpapper @Sonictherocketman would you all mind opening new issues and filling out the issue template? Thanks for providing all of the detail, but it'd be really helpful if we could track these separately because the backtraces are different. Thanks!

**Comment by DanToml** [comment]
Closing due to lack of activity. If this is still a a problem please file a new issue, including a sample project.
