### ISSUE TITLE
The coincidence of pod names in private and in global repo. How to specify private repo path instead global in podspec file?

### ISSUE THREAD

**Issue by alex-ost** [CocoaPods/CocoaPods#6438]
# Report

## What did you do?
I tried to create a pod spec with dependency from a private repo. 
After podspec configuration I tried to do "pod spec lint ." and see many warnings, like: 
 _"- WARN  | xcodebuild:  StateMachine/StateMachine/LSStateMachineDynamicAdditions.m:15:57: warning: undeclared selector 'stateMachine' [-Wundeclared-selector]"_

But it's not mine StateMachine, my stateMachine doesn't have LS prefix and this selectors. I understood that this pod placed in global repo, and my StateMachine has the same name but in private repo.

I've googled and saw many questions about dependecy specification in podspec, but no any solutions how to specify pod git path for dependency in podspec file.

## What did you expect to happen?
I expect that pod spec will work fine and will found correct repo, because now "pod spec lint ." shows incorrect linking.

## Main problem
How to specify dependency for pod from private repo in spec file? Or maybe can I change sequence of repos and set rule like "first search pods in private repo"?

### Stack
"..." - replaced private info
```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.6.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2c47f171dc85a5f4f96ea3863edeabce9ce97348
               private-podspecs - git@github.com:.../private-podspecs.git @ 05268d394709b1adb923082de4c3f2d1c12b505f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile
"..." - replaced private info
```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFramework' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFramework
  pod 'StateMachine', :git => 'git@github.com:.../framework-statemachine.git', :tag => "v1.0.1"
  target 'MyFrameworkTests' do
    inherit! :search_paths
    pod 'StateMachine', :git => 'git@github.com:.../framework-statemachine.git', :tag => "v1.0.1"
    # Pods for testing
  end

end
```

**Comment by orta** [comment]
[pod spec lint](https://guides.cocoapods.org/terminal/commands.html#pod_spec_lint) supports `--sources` which is order dependent.

Inside a Podfile the order in which you add the [sources](https://github.com/artsy/eigen/blob/a513271d8d70fd140b2245845f935908f668e6be/Podfile#L1-L2) dictates the order in which Podspecs should be found 👍

**Comment by AlexOstrynskyi-SS** [comment]
@orta hm, so it's my scheme:
framework_A - independent framework which placed in private repo, hasn't any Pods.
framework_B - framework which based on framework_A, also placed in private repo. Has Podfile with pod for framework_A.
myProject - my project. I going to add Pod for framework_B. And is it true that when framework_B will be added to myProject, it will use path for framework_A from his Podfile?

PS Thank you for `--sources`, I got "_framework_B.podspec passed validation_" :)

**Comment by AlexOstrynskyi-SS** [comment]
I tried scheme above, and got next result:
framework_B was downloaded successfully but anyway it downloaded incorrect framework_A - from global repo.

Here is Podfile for framework_B:
```
target 'framework_B' do
  # Pods for framework_B
  pod 'framework_A', :git => 'git@github.com:.../framework_A.git', :tag => "v0.0.1"
end
```

Here is Podfile for myProject:
```
target : myProject do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'framework_B', :git => 'git@github.com:.../framework_B.git'
end

```

**Comment by benasher44** [comment]
@AlexOstrynskyi-SS are these 2 separate Podfiles?

**Comment by dnkoutso** [comment]
Isnt this solved by `pod 'StateMachine', :git => 'git@github.com:.../framework-statemachine.git', :tag => "v1.0.1", :source => 'mySource'
`

**Comment by rafaelbaraldi** [comment]
I still have this problem. 
I use a private repo, it is the first source I set in my Podfile, the second one is the common Cocoapods source in Github. It works fine with the pods I set in my Podfile even if it has mutiple specifications on both repos. 
My problem is when one of my pods has as a dependency another pod that has multiple specifications. The pod referred as a dependency always use the specification that is in Cocoapods Github master repo, even if I set the dependency directly in my Podfile. I want it to use the specification that is in my private spec repo.

Any workaround or fix for this? (I'm using verison 1.4.0)

Tks :)

**Comment by rafaelbaraldi** [comment]
Ok, o managed to do it by adding the 'source' parameter in the dependency pod directly in my Podfile specifying the spec repo I want, but it does not look very nice. Would it be another way to do it that I haven't to add the dependency in my Podfile, maybe doing it in the podspec that register the dependency? 
tks again
