### ISSUE TITLE
Getting build error trying to use a static framework which contains dependencies transitively

### ISSUE THREAD

**Issue by farkasseb** [CocoaPods/CocoaPods#7140]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
`bundle update`
`bundle exec pod install`
`open CocoaPodsStaticFramworkBetaTest.xcworkspace`
`⌘+B`

## What did you expect to happen?
Build Suceeded

## What happened instead?
Build Failed

## CocoaPods Environment
`bundle exec pod env | pbcopy`

### Stack
```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.1 (17B25c)
       Xcode : 9.1 (9B37)
         Git : git version 2.14.2
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f2c58978f124dded5ed4431c62d55aa827a4ec7f
```

### Installation Source

```
Executable Path: /usr/local/lib/ruby/gems/2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 2.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'CocoaPodsStaticFramworkBetaTest' do
  pod 'TransitiveExample', :git => 'https://github.com/fandor92/transitive-example.git', :tag => 'v0.1'
end
```

## Project that demonstrates the issue
https://github.com/farkasseb/CocoaPodsStaticFramworkBetaTest

We are trying to use the latest CocoaPods (beta from source). Could you please point out what are we doing wrong with this dependency setup?

**Comment by dnkoutso** [comment]
has probably been fixed by https://github.com/CocoaPods/CocoaPods/pull/7135 but I'll @paulb777 confirm and close if true.

**Comment by farkasseb** [comment]
#7135 seems to be merged and we are experimenting with CocoaPods masters branch, so I believe this issue is still valid.

**Comment by farkasseb** [comment]
This is the output of the `bundle update` command showing which version we are using.

```
Fetching https://github.com/CocoaPods/CocoaPods.git
Fetching https://github.com/CocoaPods/Core.git
Fetching https://github.com/CocoaPods/Xcodeproj.git
Fetching https://github.com/orta/cocoapods-keys.git
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using CFPropertyList 2.3.5
Using ZenTest 4.11.1
Using i18n 0.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6
Using json 1.8.6
Using mini_portile2 2.3.0
Using bundler 1.15.4
Using claide 1.0.2
Using fuzzy_match 2.0.4
Using nap 1.1.0
Using cocoapods-deintegrate 1.0.1
Using cocoapods-downloader 1.1.3
Using cocoapods-search 1.0.0
Using cocoapods-stats 1.0.0
Using netrc 0.11.0
Using cocoapods-try 1.1.0
Using colored2 3.1.2
Using escape 0.0.4
Using fourflusher 2.0.1
Using gh_inspector 1.0.3
Using molinillo 0.6.3
Using ruby-macho 1.1.0
Using nanaimo 0.2.3
Using dotenv 2.2.1
Using highline 1.7.8
Using multipart-post 2.0.0
Using net-ssh 4.2.0
Using plist 3.1.0
Using rouge 2.0.7
Using rubyzip 1.2.1
Using sbconstants 1.2.0
Using security 0.1.3
Using unicode-display_width 1.3.0
Using RubyInline 3.12.4
Using tzinfo 1.2.3
Using nokogiri 1.8.1
Using cocoapods-plugins 1.0.0
Using cocoapods-trunk 1.3.0
Using xcodeproj 1.5.2 from https://github.com/CocoaPods/Xcodeproj.git (at master@0760750)
Using commander 4.4.3
Using faraday 0.13.1
Using net-sftp 2.1.2
Using xcpretty 0.2.8
Using terminal-table 1.8.0
Using osx_keychain 1.0.1
Using activesupport 4.2.10
Using aws-sdk-v1 1.67.0
Using faraday_middleware 0.12.2
Using cocoapods-keys 2.0.0 from https://github.com/orta/cocoapods-keys.git (at master@83b0c3f)
Using cocoapods-core 1.4.0.beta.1 from https://github.com/CocoaPods/Core.git (at master@6db1586)
Using aws-sdk 1.67.0
Using cocoapods 1.4.0.beta.1 from https://github.com/CocoaPods/CocoaPods.git (at master@1b834cf)
Using shenzhen 0.14.3
Bundle updated!
```

1b834cf seems to be the last commit on the master branch.

**Comment by paulb777** [comment]
Thanks for creating the example.

I've tracked down the issue to the need to generate a .swiftmodule directory for the static framework Modules directory. The test will pass if I restore the .swiftmodule directory from a dynamic library build to the static library build.

I'll investigate solutions tomorrow.

**Comment by farkasseb** [comment]
We verified that the issue is fixed 🎉! Thank you very much for you fast help. 👍
