### ISSUE TITLE
Errors/Warnings after pod lib create

### ISSUE THREAD

**Issue by craiggrummitt** [CocoaPods/CocoaPods#7228]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Run `pod lib create XXX`
2. Selected: "Swift" (language), "Yes" (demo application), "None" (testing frameworks), "No" (view based testing)

## What did you expect to happen?

Creation of pod without warnings / errors.

## What happened instead?

Workspace produces errors and warnings in Xcode:
1. Warning:
> Update recommended settings

This warning is easy enough to resolve following Xcode suggestions.

2. Error:
> "Code Signing Error: Signing for "..." requires a development team. Select a development team in the project editor." 
> "Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'"

These two code signing errors can be resolved by adding your team in General settings for your main and test targets.

3. Warning:
> Apple Mach-O Linker (Id) Warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/Developer/Library/Frameworks'

I've been trying to hunt this down, but haven't been able to find it. Any ideas?

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12.6 (16G1036)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 25e91b0902122ca4ee2b917c97a3fda6335464e0
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

It should be as easy as calling `pod lib create` to replicate this error.

**Comment by dnkoutso** [comment]
I think this is fixed by updating the xcodeproj to latest version. Going to close and feel free to re-open.

**Comment by craiggrummitt** [comment]
When you say 'latest version' - do you mean of the base SDK? The base SDK that 'pod lib create' sets is 'latest', which is currently 11.2.

BTW I am now using Xcode 9.2, and am still seeing the same problem.

**Comment by segiddins** [comment]
Xcodeproj, the gem. It's latest version is 1.5.6

**Comment by craiggrummitt** [comment]
Just installed latest Xcodeproj, am now on 1.5.6. I then followed my instructions in the initial report, and am still seeing the same problem. If possible could we re-open this issue?

**Comment by segiddins** [comment]
Sure, could you please upload a project we can use to reproduce the issue? Thanks!

**Comment by craiggrummitt** [comment]
Sure, it's literally as easy as following the two steps described in the "What did you do?" section above, but if you need to see a project after following those two steps, here's one: 
https://github.com/craiggrummitt/CocoaPodsTest
