### ISSUE TITLE
GoogleMobileVision GoogleSignIn duplicate symbol using Cocoapods?

### ISSUE THREAD

**Issue by chatarveer** [CocoaPods/CocoaPods#8015]
pod --version 1.5.3
Xcode version Version 9.4.1 (9F2000)

Podfile
```ruby
target 'TestGoogleLib' do
  use_frameworks!

    pod 'GoogleMobileVision'
    pod 'GoogleSignIn'
end
```

Errors in Xcode while running code

duplicate symbol _OBJC_IVAR_$_MDMPasscodeCache._localAuthenticationInfo in:

ld: 13 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dnkoutso** [comment]
Would appreciate a sample app here, this report is not very helpful. Either way I tried it myself on a sample app and successfully compiled.

**Comment by paulb777** [comment]
May need a more recent version of GoogleSignIn. Some symbol issue were fixed in recent releases. `pod repo update`.

**Comment by jtressle** [comment]
@dnkoutso @veer-suthar I'm getting the same issue.

Versions:
GoogleSignIn = 4.2.0
GoogleMobileVision = 1.3.2

I updated Pods to version 1.6.0.beta.1 and the issue persists.

**Comment by jtressle** [comment]
@paulb777 I tried `pod repo update` to no avail.  Also, I verified both pods are up to date.

**Comment by jtressle** [comment]
@dnkoutso @veer-suthar @paulb777 I was able to compile by changing GoogleSignIn to version 4.1.2.  So the problem appears to be with GoogleSignIn 4.2.0.

Hope this helps.  Thanks!

**Comment by paulb777** [comment]
Thanks @jtressle. I've reproduced the failure with 4.2.0 and workaround with 4.1.2.

This isn't a CocoaPods issue, but an issue with the builds of `GoogleSignIn` and `GoogleMobileVision` pods.

**Comment by jamiedaniel** [comment]
If using Firebase and Firestore even this work around causes the same error.
What is said is `[!] CocoaPods could not find compatible versions for pod "GoogleSignIn":
  In snapshot (Podfile.lock):
    GoogleSignIn (= 4.2.0, ~> 4.0, ~> 4.1)

  In Podfile:
    GoogleSignIn (= 4.1.2)

Specs satisfying the `GoogleSignIn (= 4.1.2), GoogleSignIn (= 4.2.0, ~> 4.0, ~> 4.1)` dependency were found, but they required a higher minimum deployment target.
`
So this is causing some issues with Firebase for me.

**Comment by paulb777** [comment]
@jamiedaniel Please share your Podfile, Podfile.lock and full command output.
