### ISSUE TITLE
Pods with dependencies that are just static frameworks should include them in their build phases

### ISSUE THREAD

**Issue by dmbagwell** [CocoaPods/CocoaPods#8075]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

* Create a custom pod with a dependency that is just a static framework
* Create a project that depends on this custom pod
* Use this workaround
```
pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```
to get around this issue
```
[!] The 'Pods-Sample' target has transitive dependencies that include static binaries: (/Users/dbagwell/Projects/Sample/FailingSample/Pods/Crashlytics/iOS/Crashlytics.framework)
```
* Run pod install
* Attempt to build the project

## What did you expect to happen?

CocoaPods should setup all the dependencies correctly in the project, and the project should build successfully.

## What happened instead?

Running pod install did not add the static framework dependencies of the custom pod's target's `Link Binary With Libraries` build phase and the project failed to build with the following error.
```
Undefined symbols for architecture x86_64:
  "_CLSLogv", referenced from:
      SamplePod.log(Swift.String) -> () in Log.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**However, manually adding the static framework dependencies of the custom pod to the target's build phase causes building to succeed.** It seems to me that this is something CocoaPods should do.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 928c1f131407f9307829803a3ecfe95ac368a4b5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

target 'Sample' do
  use_frameworks!

  pod 'SamplePod', :path => 'SamplePod'

end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```

## Project that demonstrates the issue

Here is the project that fails if you run pod install and then build: https://github.com/dmbagwell/Sample/tree/master/FailingSample
And here is a project that includes the workspace and pods project in which I have manually added the static framework dependencies to the build phase so that it will build successfully: https://github.com/dmbagwell/Sample/tree/master/WorkingSample

**Comment by paulb777** [comment]
@dnkoutso Yes this could be the missing -ObjC in `Other Linker Flags` issue fixed by the 1.6.0.beta.1 PR - #7946.

**Comment by dbagwell** [comment]
I will note that I have also tried using 1.6.0.beta.1 and see the same results. The static frameworks are still not added to the `Link Binary With Libraries` build phase, and the linking still fails, unless I add them to the build phase manually.

**Comment by RbBtSn0w** [comment]
> The best solution is to add `s.static_framework = true` to SamplePod.podspec.
> 
> It would be possible to make the code in https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/target/build_settings.rb add the static frameworks to the `OTHER_LDFLAGS` setting but that would lead to duplicate library warnings at runtime and the resulting risk of undefined behavior.
> 
> Dynamic libraries should not depend on static frameworks and the `pre_install` code in the Podfile is dangerous.

can we define, like this

```ruby
 pod 'AFNetworking',  '0.1.0',  : static_framework  => true
```

**Comment by DineshPearson** [comment]
> * [x]  I've read and understood the [_CONTRIBUTING_ guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈
> 
> # Report
> ## What did you do?
> * Create a custom pod with a dependency that is just a static framework
> * Create a project that depends on this custom pod
> * Use this workaround
> 
> ```
> pre_install do |installer|
>     # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
>     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> end
> ```
> 
> to get around this issue
> 
> ```
> [!] The 'Pods-Sample' target has transitive dependencies that include static binaries: (/Users/dbagwell/Projects/Sample/FailingSample/Pods/Crashlytics/iOS/Crashlytics.framework)
> ```
> 
> * Run pod install
> * Attempt to build the project
> 
> ## What did you expect to happen?
> CocoaPods should setup all the dependencies correctly in the project, and the project should build successfully.
> 
> ## What happened instead?
> Running pod install did not add the static framework dependencies of the custom pod's target's `Link Binary With Libraries` build phase and the project failed to build with the following error.
> 
> ```
> Undefined symbols for architecture x86_64:
>   "_CLSLogv", referenced from:
>       SamplePod.log(Swift.String) -> () in Log.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> **However, manually adding the static framework dependencies of the custom pod to the target's build phase causes building to succeed.** It seems to me that this is something CocoaPods should do.
> 
> ## CocoaPods Environment
> ### Stack
> ```
>    CocoaPods : 1.5.3
>         Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
>     RubyGems : 2.5.2.3
>         Host : Mac OS X 10.13.6 (17G65)
>        Xcode : 9.4.1 (9F2000)
>          Git : git version 2.15.2 (Apple Git-101.1)
> Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
> Repositories : master - https://github.com/CocoaPods/Specs.git @ 928c1f131407f9307829803a3ecfe95ac368a4b5
> ```
> 
> ### Installation Source
> ```
> Executable Path: /usr/local/bin/pod
> ```
> 
> ### Plugins
> ```
> cocoapods-deintegrate : 1.0.2
> cocoapods-plugins     : 1.0.0
> cocoapods-search      : 1.0.0
> cocoapods-stats       : 1.0.0
> cocoapods-trunk       : 1.3.1
> cocoapods-try         : 1.1.0
> ```
> 
> ### Podfile
> ```ruby
> platform :ios, '10.0'
> 
> target 'Sample' do
>   use_frameworks!
> 
>   pod 'SamplePod', :path => 'SamplePod'
> 
> end
> 
> pre_install do |installer|
>     # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
>     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> end
> ```
> 
> ## Project that demonstrates the issue
> Here is the project that fails if you run pod install and then build: https://github.com/dmbagwell/Sample/tree/master/FailingSample
> And here is a project that includes the workspace and pods project in which I have manually added the static framework dependencies to the build phase so that it will build successfully: https://github.com/dmbagwell/Sample/tree/master/WorkingSample

Hi, did you found Any solution for this issue ?
