### ISSUE TITLE
watchOS builds cannot be installed via TestFlight

### ISSUE THREAD

**Issue by robbiet480** [CocoaPods/CocoaPods#8754]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Hi there,

Mostly just opening this issue for others that are experiencing it, hope that's okay. 

Recently, it appears that Apple changed how watchOS builds are installed via TestFlight. Whatever they did now causes builds including _certain_ CocoaPods to not be installable. There's two primary discussion points for this right now, [this thread on the Developer Forums](https://forums.developer.apple.com/message/358909) and [this Stack Overflow](https://stackoverflow.com/questions/55886569/testflight-couldnt-install-on-apple-watch) question.

Apple has been alerted but wondering if the CocoaPods team can shed any light that will get this fixed faster for all of us (there's probably 15 developers involved total thus far).

Thanks!

**Comment by rawmean** [comment]
Console logs show that TestFlight thinks CocoaPods frameworks (embedded in the watch app extension) are watch apps and when it doesn't see a watch app with that bundleID it fails to install the entire watch app on the watch:
`[ACXDeviceConnectionClient fetchInfoForApplicationWithBundleID:forDeviceWithPairingID:completion:]: 424: No watch app found with bundle ID org.cocoapods.ObjectMapper`

**Comment by robbiet480** [comment]
Oh yeah, might be helpful if I provided some more context 😛

I'm seeing a similar message as @rawmean, `[ACXDeviceConnectionClient fetchInfoForApplicationWithBundleID:forDeviceWithPairingID:completion:]: 424: No watch app found with bundle ID org.cocoapods.XCGLogger`

@lgauthier is also seeing similar, `[ACXDeviceConnectionClient fetchInfoForApplicationWithBundleID:forDeviceWithPairingID:completion:]: 424: No watch app found with bundle ID org.cocoapods.CocoaLumberjack`

**Comment by antonbremer** [comment]
Another similar issue here.
`[ACXDeviceConnectionClient fetchInfoForApplicationWithBundleID:forDeviceWithPairingID:completion:]: 424: No watch app found with bundle ID org.cocoapods.SwiftyJSON

**Comment by rawmean** [comment]
> Another similar issue here.
> `[ACXDeviceConnectionClient fetchInfoForApplicationWithBundleID:forDeviceWithPairingID:completion:]: 424: No watch app found with bundle ID org.cocoapods.SwiftyJSON`

Please also file a bug report with apple: https://developer.apple.com/bug-reporting

**Comment by lgauthier** [comment]
I also did a number of tests the other day when I was trying to narrow down the problem. We have CocoaLumberjack in our watch app and we see this console log:

```default	10:35:02.940187 -0500	appconduitd	0x16d67b000 -[ACXDeviceConnectionClient fetchInfoForApplicationWithBundleID:forDeviceWithPairingID:completion:]: 424: No watch app found with bundle ID org.cocoapods.CocoaLumberjack```

To figure out whether it was only an issue with CocoaLumberjack, I also removed CocoaLumberjack and tried installing a build with AFNetworking added to our watch app and a build with Alamofire. Both installed fine. So, there appears to be a growing list of pods that have the issue, and some pods are fine.

I think this is the general list of pods confirmed to have the issue from what I've seen so far:

- CocoaLumberjack
- ObjectMapper
- SwiftyJSON
- XCGLogger

**Comment by rawmean** [comment]
> I also did a number of tests the other day when I was trying to narrow down the problem. We have CocoaLumberjack in our watch app and we see this console log:
> 
> `default	10:35:02.940187 -0500	appconduitd	0x16d67b000 -[ACXDeviceConnectionClient fetchInfoForApplicationWithBundleID:forDeviceWithPairingID:completion:]: 424: No watch app found with bundle ID org.cocoapods.CocoaLumberjack`
> 
> To figure out whether it was only an issue with CocoaLumberjack, I also removed CocoaLumberjack and tried installing a build with AFNetworking added to our watch app and a build with Alamofire. Both installed fine. So, there appears to be a growing list of pods that have the issue, and some pods are fine.
> 
> I think this is the general list of pods confirmed to have the issue from what I've seen so far:
> 
> * CocoaLumberjack
> * ObjectMapper
> * SwiftyJSON
> * XCGLogger

Thanks. For me it's the ObjectMapper. Now there are multiple entities involved: Apple, CocoaPods and the authors of these libraries. This makes finding a solution very difficult. This is why I hate using third-party libraries.

**Comment by dnkoutso** [comment]
Would love to isolate this down to a smaller reason and determine if it's CocoaPods fault or not.

**Comment by robbiet480** [comment]
Senior adviser at Apple reached out to me yesterday afternoon to tell me they are working the problem with no estimated time to fix.

**Comment by robbiet480** [comment]
Adding another failing Pod to the list, [Surge](https://github.com/mattt/Surge). Used by [Gyroscope](https://gyrosco.pe) (cc @myusuf3).

**Comment by robbiet480** [comment]
@ffried @tristanhimmelman @wongzigii @DaveWoodCom @mattt Do you have any ideas why your projects, when installed via CocoaPods, would cause watchOS TestFlight builds to fail to install? As you can see from the above comments so far most people have reported issues with your projects specifically and I don't think there is much hope that Apple will be fixing this in a timely manner so it may be best to attempt to fix in CocoaPods or your projects. Also, sorry to directly tag all of you but thought it would be better to do it this way instead of opening individual issues in each of your projects. Thanks in advance for any information you can provide to get all of our apps working again.

**Comment by mattt** [comment]
@robbiet480 The only thing that comes to mind is that Surge links against the Accelerate framework, which is unusual (especially for a watchOS target) and has complex hardware-dependent capabilities. It also doesn't help that Accelerate is an umbrella framework. One possible lead: the [documentation for Accelerate](https://developer.apple.com/documentation/accelerate) lists watchOS 4.0+ as the SDK, but [Surge.podspec](https://github.com/mattt/Surge/blob/master/Surge.podspec) sets a minimum watchOS target of 3.0 (reason being, it only uses the sub-frameworks of Accelerate available in watch OS <= 3.0).

**Comment by rawmean** [comment]
> Senior adviser at Apple reached out to me yesterday afternoon to tell me they are working the problem with no estimated time to fix.

I received an email from Apple DTS saying basically the same thing.

**Comment by robbiet480** [comment]
Apple told me on Friday it was fixed. It was not fixed. I waited until a few hours ago to test again just in case it was a rollout delay and it's still not fixed. I've told Apple as much and provided the new details they wanted (screenshot of error, how I got the error and exact timestamp).

**Comment by rawmean** [comment]
> Apple told me on Friday it was fixed. It was not fixed. I waited until a few hours ago to test again just in case it was a rollout delay and it's still not fixed. I've told Apple as much and provided the new details they wanted (screenshot of error, how I got the error and exact timestamp).

It's not fixed. This is a TestFlight app problem which started when Apple released the 2.2.1 version of TestFlight ~ 2 weeks ago. For the problem to be fixed, Apple needs to update TestFlight which they haven't yet.

**Comment by robbiet480** [comment]
@rawmean Actually based on the timeline i've seen, everything was working fine until a few days after the update... that may just be confused timelines or delayed updates though.

**Comment by meyumeapps** [comment]
28/04 was when our uploaded build failed.

Also, I noticed, previous (working) builds won't install on the watch either.

**Comment by robbiet480** [comment]
Apple got back to me this morning saying they are getting the engineering team to take a look and also forwarded the two radar numbers to them for further investigation. To everyone else that has a case open with Apple, might be good to reference my case number with your point of contact and I can do the same. My case number is 20000050632760. Will keep you posted of course.

**Comment by rawmean** [comment]
Apple got back to me saying that the problem is fixed. I also told them that it's not fixed.
They also closed my bug report case stating that it's a duplicate of another case, but they can't tell me the resolution to that other bug report. Disappointing...
I'll reference your case number.

**Comment by meyumeapps** [comment]
My case number: 20000051053371

**Comment by robbiet480** [comment]
My beta testers are now reporting builds can be installed again.  I am seeing the same. Anyone else?

**Comment by rawmean** [comment]
> My beta testers are now reporting builds can be installed again. I am seeing the same. Anyone else?

Same here. It's resolved. I wasted 3 days trying to fix this thinking that the problem was on my side.

**Comment by meyumeapps** [comment]
Nope, still not working for me.

Did you have to upload a new build?

**Comment by robbiet480** [comment]
@meyumeapps I did not.

**Comment by rawmean** [comment]
> Nope, still not working for me.
> 
> Did you have to upload a new build?

I did not upload a new build and TestFlight is now installing the same old build that it refused to install previously.
The problem that you are encountering may be due to a different reason. Are you getting the same error in the logs related to cocoaPods that is stated above? If not, then this thread is unrelated to the issue that you are experiencing.

**Comment by robbiet480** [comment]
I'll also add that I still haven't been told by Apple that this issue has been fixed, so maybe it is a multistep fix or staged rollout which means you haven't yet seen it locally. I'd try asking your beta testers if they are able to install it now.

**Comment by meyumeapps** [comment]
I'm still getting this when I try and installed the watch app:

`0x16bd4f000 -[ACXDeviceConnectionClient fetchInfoForApplicationWithBundleID:forDeviceWithPairingID:completion:]: 424: No watch app found with bundle ID org.cocoapods.XCGLogger`

**Comment by robbiet480** [comment]
I did have a funny thought earlier that maybe this mornings global TestFlight outage was related to them fixing this hah. 

@meyumeapps still haven’t gotten the all clear from Apple. Will let you know.

**Comment by meyumeapps** [comment]
Mine is back today ... after I got an email from Apple saying that it had been fixed.

It's almost like they are fixing on a case by case basis?

**Comment by robbiet480** [comment]
Just pinged my Apple support person since I haven't heard anything in 3 days. Will let you know what they say.

**Comment by robbiet480** [comment]
@meyumeapps Apple reported to me (on Friday, but I was traveling) that their internal teams report the issue is resolved. I've told them that it is working for me now, I suggest that if you are still having issues to follow up with Apple on your own and reference my case # 20000050632760.
