### ISSUE TITLE
Xcode 11.1 GM warning: Enable Base Internationalization

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#9187]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Update to Xcode 11.1 GM running CocoaPods 1.8.0. The `install! 'cocoapods', :generate_multiple_pod_projects => true` option was previously enabled and didn't show warnings on Xcode 11.0.

This issue is a duplicate / resurfacing of the closed issue here: https://github.com/CocoaPods/CocoaPods/issues/8494

## What did you expect to happen?

No new warnings.

## What happened instead?

Warnings appeared for "Enable Base Internationalization" on every generated Xcode project - except for the Pods project itself.

### Stack

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0
Ruby lib dir : /Users/chrisbal/.rbenv/versions/2.5.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 5e06cc7f3dce3991f5eed82d5e80e3bd0425009d
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/chrisbal/Documents/xxxxxxxxxx-iOS/vendor/bundle/ruby/2.5.0/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
slather               : 2.4.7
```

### Podfile

```ruby
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
inhibit_all_warnings!

install! 'cocoapods', :generate_multiple_pod_projects => true

project 'XXXXXXX', 'Debug' => :debug, 'Previews' => :debug

def shared
    pod 'KeychainAccess'
    pod 'BonMot'
    pod 'Alamofire', '5.0.0-rc.2'
    pod 'Anchorage'
    pod 'Swiftilities'
    pod 'Sodium'

    pod 'Poly', :git => 'https://github.com/mattpolzin/Poly.git'
    pod 'MP-JSONAPI', :git => 'https://github.com/mattpolzin/JSONAPI.git'
    pod 'GRDB.swift/SQLCipher'
    pod 'SQLCipher', :modular_headers => true
end

def stubs
  inherit! :search_paths
  pod 'OHHTTPStubs/Swift'
end

def firebase
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
end

target 'XXXXXXX' do
  pod 'SimulatorStatusMagic', :configurations => ['Debug', 'Previews'], :modular_headers => true
  pod 'EFQRCode'
  firebase()
  pod 'Crashlytics'
  pod 'AppCenter/Distribute', :configurations => ['Sprint', 'Develop']

  target 'XXXXXXXTests' do
    pod 'OHHTTPStubs/Swift'
    firebase()
  end

  shared()
end

target 'ServicesTests' do
  shared()
  stubs()
end

target 'Services' do
  shared()
end

pod 'SwiftGen'
pod 'SwiftLint'
pod 'LicensePlist'

# https://github.com/CocoaPods/CocoaPods/issues/8069#issuecomment-420044112
post_install do |installer|
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
      end
    end
  end
end
```

## Project that demonstrates the issue

n/a

**Comment by dnkoutso** [comment]
Had to ship a 1.81. for another fix. Pushing this to 1.8.2

**Comment by Coeur** [comment]
@dnkoutso 1.8.3 was released without it I believe. Is it scheduled for 1.8.4?

**Comment by liamnichols** [comment]
So a brand new Xcode Project created using Xcode 11.1 includes the `Base` value by default:

<img width="728" alt="Screenshot 2019-10-09 at 13 16 17" src="https://user-images.githubusercontent.com/482871/66480624-049efb80-ea97-11e9-867c-d01635b96f42.png">

So should the default value of `known_regions` in Xcodeproj not match this now? 

```
$ more project.pbxproj | grep knownRegions -A 3
			knownRegions = (
				en,
				Base,
			);
```

As it currently only includes `en`:

https://github.com/CocoaPods/Xcodeproj/blob/43adc38ed70e25427a09727e6714ffa210d32b4d/lib/xcodeproj/project/object/root_object.rb#L43-L45

(#8494 was fixed by changing `English` to `en` so I guess these are different)

I'm not completely familiar with the internals of CocoaPods but to me, this would suggest that the fix needs applying to Xcodeproj and then a `bundle update xcodeproj` should resolve things?

**Comment by dnkoutso** [comment]
Removing milestone from this issue as it is fixed as part of the Xcodeproj gem and a CocoaPods release is not required.

**Comment by chrisballinger** [comment]
Thank you for the fix!!

**Comment by benguild** [comment]
I'm still seeing this even on Version 11.0 (11A420a) with latest Cocoa Pods and `xcodeproj` gems. 🤔

**Comment by dnkoutso** [comment]
We did not ship Xcodeproj gem update yet.

**Comment by chuck-imperato** [comment]
Thanks for the fix.  Looking forward to this 👍

**Comment by dnkoutso** [comment]
Shipped Xcodeproj 1.13.0.

**Comment by chrisballinger** [comment]
Thank you!

**Comment by mohpor** [comment]
What am I missing? I'm still getting a horrible amount of this warnings on my project! Is there a solution I'm not seeing? (pod version: 1.8.4)
